# The State of Tax Justice: Race to the Bottom. Comparison between CITs in 2016 and 2017.


## 0. Load packages

In [1]:
# Packages
import pandas as pd
import numpy as np
import tjn_tools
from config import *

# Show columns and select data format
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

[TJN TOOLS: Data processing] Module loaded.
[TJN TOOLS: Other functions] Module loaded.
[TJN TOOLS: Paths] Module loaded. Sharepoint FOUND at /Users/mariocuendagarcia/Library/CloudStorage/OneDrive-SharedLibraries-TaxJusticeNetworkLtd

## Step 1. Import data

In [2]:
cbcr_sample = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Exclude country groups
cbcr_sample = cbcr_sample[~cbcr_sample['iso_partner'].isin(non_countries)]

cbcr_sample

,iso_parent,parent_jurisdiction,iso_partner,partner_jurisdiction,year,unrelated_party_revenues,profit_loss_before_income_tax,adjusted_profit_loss_before_income_tax,income_tax_paid_on_cash_basis,income_tax_accrued_current_year,n_employees,tangible_assets_except_cash,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,n_cbcr,n_cbcr_groups,n_entities,profit_loss_before_income_tax_corrected,ln_profit_loss_before_income_tax_corrected,ln_unrelated_party_revenues,ln_n_employees,ln_tangible_assets_except_cash,ln_stated_capital,ln_total_revenues,ln_related_party_revenues,ln_holding_or_managing_ip,etr_domestic,etr_domestic_corrected,etr_foreign,etr_foreign_corrected,etr_average,etr_average_corrected,cit,gdp_current_usd,population,gdp,wage_monthly,payroll,ln_wage_monthly,ln_gdp_current_usd,ln_population,gvt_health_expenditure,ln_gvt_health_expenditure,tax_revenue_pct_gdp,tax_revenue_current_usd,cthi_2021_share,cthi_2021_score,region_tjn,ukt,gbr_oct,nld_oct,oecd_oct,oecd,eu
0,ARE,United Arab Emirates,AFG,Afghanistan,2021,"143,907,630.00","-46,006,802.00",NaN,"42,927,479.00",0.00,"3,564.00","78,832,974.00","48,663,869.00","148,803,203.00","4,895,573.00",NaN,5.00,5.00,18.00,"-46,006,802.00",0.00,18.78,8.18,18.18,17.70,18.82,15.40,NaN,NaN,NaN,0.07,0.07,0.07,0.07,0.20,"14,266,499,429.87","40,099,462.00",NaN,171.87,"7,350,707.23",5.15,23.38,17.51,"107,697,735.61",18.49,NaN,NaN,NaN,NaN,Asia,0.00,0.00,0.00,0.00,0.00,0.00
1,ARE,United Arab Emirates,AGO,Angola,2021,"171,764,219.00","17,925,795.00",NaN,"13,390,865.00","9,822,146.00","3,249.00","22,250,946.00","10,236,316.00","171,764,219.00",0.00,NaN,4.00,4.00,10.00,"17,925,795.00",16.70,18.96,8.09,16.92,16.14,18.96,0.00,NaN,NaN,NaN,0.36,0.36,0.36,0.36,0.25,"66,505,129,987.72","34,503,774.00",NaN,143.61,"5,598,910.73",4.97,24.92,17.36,"1,279,772,420.68",20.97,NaN,NaN,NaN,NaN,Africa,0.00,0.00,0.00,0.00,0.00,0.00
2,ARE,United Arab Emirates,ARE,United Arab Emirates,2021,"201,000,000,000.00","31,538,024,664.00",NaN,"136,782,996.00","61,896,681.00","581,795.00","342,000,000,000.00","443,000,000,000.00","257,000,000,000.00","56,775,290,388.00",96.00,59.00,59.00,"4,462.00","31,538,024,664.00",24.17,26.03,13.27,26.56,26.82,26.27,24.76,4.57,0.03,0.03,0.34,0.35,0.20,0.20,0.00,"415,178,792,756.98","9,365,145.00",NaN,"3,161.18","22,069,905,037.20",8.06,26.75,16.05,"14,119,521,288.48",23.37,0.54,"2,222,218,203.26",0.04,98.33,Asia,0.00,0.00,0.00,0.00,0.00,0.00
3,ARE,United Arab Emirates,ARG,Argentina,2021,"297,786,434.00","35,504,518.00",NaN,"7,470,407.00","13,543,107.00","2,007.00","150,688,454.00","92,323,233.00","297,786,434.00",0.00,NaN,6.00,6.00,16.00,"35,504,518.00",17.39,19.51,7.60,18.83,18.34,19.51,0.00,NaN,0.17,0.19,0.28,0.29,0.25,0.26,0.30,"487,902,572,164.35","45,808,747.00",NaN,544.82,"13,121,420.80",6.30,26.91,17.64,"29,899,372,168.89",24.12,11.47,"55,955,195,677.26",0.00,32.13,Latin America,0.00,0.00,0.00,0.00,0.00,0.00
4,ARE,United Arab Emirates,ARM,Armenia,2021,"12,587,092.00","-321,915.00",NaN,0.00,0.00,327.00,"4,594,136.00","29,657,109.00","12,587,092.00",0.00,NaN,2.00,2.00,3.00,"-321,915.00",0.00,16.35,5.79,15.34,17.21,16.35,0.00,NaN,NaN,NaN,0.44,0.45,0.44,0.45,0.18,"13,878,908,628.94","2,790,974.00",NaN,259.16,"1,016,959.54",5.56,23.35,14.84,"303,765,192.71",19.53,22.00,"3,053,499,345.31",NaN,NaN,Asia,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14879,ZAF,South Africa,ZWE,Zimbabwe,2017,"954,173,462.00","212,146,066.00",NaN,"71,754,179.00","83,024,004.00","19,560.00","1,834,868,152.00","279,445,783.00","1,483,815,457.00","529,641,995.00",NaN,21.00,21.00,45.00,"212,146,066.00",19.17,20.68,9.88,21.33,19.45,21.12,20.09,NaN,NaN,NaN,0.18,0.18,0.18,0.18,0.26,"17,584,890,936.65","14,751,101.00",NaN,255.97,"60,080,926.32",5.55,23.59,16.51,"341,835,130.00",19.65,15.87,"2,791,491,447.98",NaN,NaN,Africa,0.00,0.00,0.00,0.00,0.00,0.00
14880,ZAF,South Africa,ZWE,Zimbabwe,2018,"2,147,110,196.00","559,555,834.00",NaN,"79,235,577.00","94,891,364.00","22,423.00","2,321,217,790.00","285,987,601.00","2,749,168,582.00","602,058,386.00",5.00,21.00,21.00,79.00,"559,555,834.00",20.14,21.49,10.02,21.57,19.47,21.73,20.22,1.79,NaN,NaN,0.18,0.18,0.18,0.18,0.26,"34,156,069,918.06","15,052,184.00",NaN,255.97,"68,874,980.11",5.55,24.25,16.53,"589,006,540.00",20.19,7.21,"2,464,280,179.53",NaN,NaN,Africa,0.00,0.00,0.00,0.00,0.00,0.00
14881,ZAF,South Africa,ZWE,Zimbabwe,2019,"1,355,510,826.00","545,490,828.00",NaN,"64,219,685.00","25,753,691.00","22,893.00","2,257,220,307.00","82,012,519.00","2,014,765,623.00","659,254,797.00",NaN,19.00,19.00,81.00,"545,490,828.00",20.12,21.03,10.04,21.54,18.22,21.42,20.31,NaN,NaN,NaN,0.19,0.19,0.19,0.19,0.26,"21,832,234,925.50","15,354,608.00",NaN,255.97,"70,318,642.45",5.55,23.81,16.55,"120,051,500.00",18.60,NaN,NaN,NaN,NaN,Africa,0.00,0.00,0.00,0.00,0.00,0.00
14882,ZAF,South Africa,ZWE,Zimbabwe,2020,"1,257,117,893.00","554,591,990.80",NaN,"114,847,167.00","117,896,353.20","24,829.00","2,227,358,757.00","473,678,805.80","2,119,985,506.00","862,867,613.50",26.00,30.00,30.00,83.00,"554,591,990.80",20.13,20.95,10.12,21.52,19.98,21.47,20.58,3.30,NaN,NaN,0.18,0.18,0.18,0.18,0.25,"21,509,698,406.11","15,669,666.00",NaN,255.97,"76,265,302.64",5.55,23.79,16.57,"175,429,800.00",18.98,NaN,NaN,NaN,NaN,Africa,0.00,0.00,0.00,0.00,0.00,0.00
14883,ZAF,South Africa,ZWE,Zimbabwe,2021,"2,748,411,380.00","1,731,955,756.00",NaN,"399,325,448.00","388,179,620.00","23,430.00","2,872,433,244.00","335,365,757.00","4,201,217,005.00","1,452,805,625.00",0.00,21.00,21.00,35.00,"1,731,955,756.00",21.27,21.73,10.06,21.78,19.63,22.16,21.10,0.00,NaN,NaN,0.18,0.18,0.18,0.18,0.25,"28,371,238,665.51","15,993,524.00",NaN,157.37,"44,244,743.40",5.06,24.07,16.59,"328,520,941.52",19.61,NaN,NaN,NaN,NaN,Africa,0.00,0.00,0.00,0.00,0.00,0.00

## Step 2. Create samples with CIT 2016 and 2021

### Step 2.1. Create a sample with the CIT of 2016.

In [3]:
# Keep cit_sample
cit_sample_2016 = cbcr_sample[cbcr_sample['year'] == 2016].copy()

# Keep iso_parent, year and cit
cit_sample_2016 = cit_sample_2016[['iso_partner', 'cit']]

# Drop duplicates
cit_sample_2016 = cit_sample_2016.drop_duplicates()

# Rename cit as cit_2016
cit_sample_2016 = cit_sample_2016.rename(columns={'cit': 'cit_2016'})

# Sort by iso_partner
cit_sample_2016 = cit_sample_2016.sort_values(by=['iso_partner'])

cit_sample_2016

      iso_partner  cit_2016
13597         ABW      0.25
14463         AFG      0.20
2816          AGO      0.30
8515          ALB      0.15
10669         AND      0.00
...           ...       ...
728           VNM      0.22
11207         YEM      0.20
746           ZAF      0.28
3564          ZMB      0.35
14456         ZWE      0.26

[183 rows x 2 columns]

### Step 2.2. Create a sample with the CIT of 2021.

In [4]:
# Keep cit_sample
cit_sample_2021 = cbcr_sample[cbcr_sample['year'] == 2021].copy()

# Keep iso_parent, year and cit
cit_sample_2021 = cit_sample_2021[['iso_partner', 'cit']]

# Drop duplicates
cit_sample_2021 = cit_sample_2021.drop_duplicates()

# Rename cit as cit_2016
cit_sample_2021 = cit_sample_2021.rename(columns={'cit': 'cit_2021'})

# Sort by iso_partner
cit_sample_2021 = cit_sample_2021.sort_values(by=['iso_partner'])

cit_sample_2021

     iso_partner  cit_2021
3578         ABW      0.25
0            AFG      0.20
1            AGO      0.25
797          AIA      0.00
1994         ALB      0.15
...          ...       ...
4948         XKV      0.10
148          YEM      0.20
149          ZAF      0.28
756          ZMB      0.35
150          ZWE      0.25

[211 rows x 2 columns]

## Step 3. Merge the datasets and generate the difference between CITs

In [5]:
# Merge cit_sample_2016 and cit_sample_2021
comparison_cits = pd.merge(cit_sample_2016, cit_sample_2021, how='inner', on='iso_partner')

# Sort by iso_partner
comparison_cits = comparison_cits.sort_values(by=['iso_partner'])

# Generate decrease in CIT by subtracting cit_2016 from cit
comparison_cits['decrease_cit'] = comparison_cits['cit_2021'] - comparison_cits['cit_2016']

comparison_cits

    iso_partner  cit_2016  cit_2021  decrease_cit
0           ABW      0.25      0.25          0.00
1           AFG      0.20      0.20          0.00
2           AGO      0.30      0.25         -0.05
3           ALB      0.15      0.15          0.00
4           AND      0.00      0.00          0.00
..          ...       ...       ...           ...
176         VNM      0.22      0.20         -0.02
177         YEM      0.20      0.20          0.00
178         ZAF      0.28      0.28          0.00
179         ZMB      0.35      0.35          0.00
180         ZWE      0.26      0.25         -0.01

[181 rows x 4 columns]

## Step 4. Comparative Results.

### Step 4.1 Number of countries that decreased their CIT, and average decrease

In [6]:
# Filter Negative Values
decrease_cit = comparison_cits[comparison_cits['decrease_cit'] < 0]

# Estimate the Average decrease in CIT
decrease_cit['decrease_cit'].mean()
print('The average decrease in CIT is:', decrease_cit['decrease_cit'].mean())

# How many values does the dataset have?
decrease_cit['decrease_cit'].count()
print('This is the number of countries that decreased their CIT:', decrease_cit['decrease_cit'].count())

decrease_cit

The average decrease in CIT is: -0.05891280210526315
This is the number of countries that decreased their CIT: 38

    iso_partner  cit_2016  cit_2021  decrease_cit
2           AGO      0.30      0.25         -0.05
6           ARG      0.35      0.30         -0.05
7           ARM      0.20      0.18         -0.02
8           ASM      0.44      0.34         -0.10
12          BEL      0.34      0.25         -0.09
21          BLZ      0.25      0.00         -0.25
25          BRB      0.25      0.06         -0.20
29          CAN      0.27      0.26         -0.01
30          CHE      0.21      0.20         -0.01
36          COG      0.30      0.28         -0.02
37          COL      0.40      0.31         -0.09
54          FRA      0.34      0.28         -0.06
57          GBR      0.20      0.19         -0.01
65          GRC      0.29      0.22         -0.07
66          GRL      0.32      0.27         -0.05
68          GUM      0.35      0.21         -0.14
71          HRV      0.20      0.18         -0.02
72          HUN      0.19      0.09         -0.10
73          IDN      0.25      0.22         -0.03
75          IND      0.48      0.25         -0.23
80          ISR      0.25      0.23         -0.02
81          ITA      0.31      0.28         -0.03
85          JPN      0.30      0.30         -0.00
93          LAO      0.24      0.20         -0.04
98          LKA      0.28      0.24         -0.04
101         LUX      0.29      0.25         -0.04
126         NOR      0.25      0.22         -0.03
129         PAK      0.32      0.29         -0.03
135         PRI      0.39      0.38         -0.02
148         SLE      0.30      0.25         -0.05
152         SVK      0.22      0.21         -0.01
154         SWE      0.22      0.21         -0.01
159         TGO      0.29      0.27         -0.02
161         TJK      0.24      0.23         -0.01
164         TUN      0.25      0.15         -0.10
175         VIR      0.39      0.23         -0.15
176         VNM      0.22      0.20         -0.02
180         ZWE      0.26      0.25         -0.01

### Step 4.2. Number of countries that increased their CIT, and average decrease

In [7]:
# Filter Positive Values
increase_cit = comparison_cits[comparison_cits['decrease_cit'] > 0]

# Estimate the Average decrease in CIT
increase_cit['decrease_cit'].mean()
print('The average decrease in CIT is:', increase_cit['decrease_cit'].mean())

# How many values does the dataset have?
increase_cit['decrease_cit'].count()
print('This is the number of countries that decreased their CIT:', increase_cit['decrease_cit'].count())

increase_cit

The average decrease in CIT is: 0.036201477499999996
This is the number of countries that decreased their CIT: 16

    iso_partner  cit_2016  cit_2021  decrease_cit
15          BGD      0.25      0.33          0.08
31          CHL      0.24      0.27          0.03
43          DEU      0.30      0.30          0.00
47          ECU      0.22      0.25          0.03
91          KOR      0.24      0.28          0.03
94          LBN      0.15      0.17          0.02
102         LVA      0.15      0.20          0.05
128         OMN      0.12      0.15          0.03
131         PER      0.28      0.29          0.01
136         PRT      0.29      0.32          0.02
151         SSD      0.20      0.25          0.05
153         SVN      0.17      0.19          0.02
163         TTO      0.25      0.30          0.05
165         TUR      0.20      0.25          0.05
166         TWN      0.17      0.20          0.03
172         UZB      0.07      0.15          0.07

### Step 4.3. Number of countries that changed their CIT, and average change

In [8]:
# Filter 0 Values
cit_unchanged = comparison_cits[comparison_cits['decrease_cit'] != 0]

# Estimate the Average decrease in CIT
cit_unchanged['decrease_cit'].mean()
print('The average decrease in CIT is:', cit_unchanged['decrease_cit'].mean())

# How many values does the dataset have?
cit_unchanged['decrease_cit'].count()
print('This is the number of countries that changed their CIT:', cit_unchanged['decrease_cit'].count(), 'values')

cit_unchanged

The average decrease in CIT is: -0.030730793333333336
This is the number of countries that changed their CIT: 54 values

    iso_partner  cit_2016  cit_2021  decrease_cit
2           AGO      0.30      0.25         -0.05
6           ARG      0.35      0.30         -0.05
7           ARM      0.20      0.18         -0.02
8           ASM      0.44      0.34         -0.10
12          BEL      0.34      0.25         -0.09
15          BGD      0.25      0.33          0.08
21          BLZ      0.25      0.00         -0.25
25          BRB      0.25      0.06         -0.20
29          CAN      0.27      0.26         -0.01
30          CHE      0.21      0.20         -0.01
31          CHL      0.24      0.27          0.03
36          COG      0.30      0.28         -0.02
37          COL      0.40      0.31         -0.09
43          DEU      0.30      0.30          0.00
47          ECU      0.22      0.25          0.03
54          FRA      0.34      0.28         -0.06
57          GBR      0.20      0.19         -0.01
65          GRC      0.29      0.22         -0.07
66          GRL      0.32      0.27         -0.05
68          GUM      0.35      0.21         -0.14
71          HRV      0.20      0.18         -0.02
72          HUN      0.19      0.09         -0.10
73          IDN      0.25      0.22         -0.03
75          IND      0.48      0.25         -0.23
80          ISR      0.25      0.23         -0.02
81          ITA      0.31      0.28         -0.03
85          JPN      0.30      0.30         -0.00
91          KOR      0.24      0.28          0.03
93          LAO      0.24      0.20         -0.04
94          LBN      0.15      0.17          0.02
98          LKA      0.28      0.24         -0.04
101         LUX      0.29      0.25         -0.04
102         LVA      0.15      0.20          0.05
126         NOR      0.25      0.22         -0.03
128         OMN      0.12      0.15          0.03
129         PAK      0.32      0.29         -0.03
131         PER      0.28      0.29          0.01
135         PRI      0.39      0.38         -0.02
136         PRT      0.29      0.32          0.02
148         SLE      0.30      0.25         -0.05
151         SSD      0.20      0.25          0.05
152         SVK      0.22      0.21         -0.01
153         SVN      0.17      0.19          0.02
154         SWE      0.22      0.21         -0.01
159         TGO      0.29      0.27         -0.02
161         TJK      0.24      0.23         -0.01
163         TTO      0.25      0.30          0.05
164         TUN      0.25      0.15         -0.10
165         TUR      0.20      0.25          0.05
166         TWN      0.17      0.20          0.03
172         UZB      0.07      0.15          0.07
175         VIR      0.39      0.23         -0.15
176         VNM      0.22      0.20         -0.02
180         ZWE      0.26      0.25         -0.01