# Data on Australia

Requested by Alex at the end of 2024 due to the CBCR Law in Australia.

## 0. Load Packages

In [1]:
# Packages
import pandas as pd
import numpy as np
import tjn_tools
from config import *

# Show columns and select data format
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
# Reset display.max_rows to default
pd.reset_option('display.max_rows')

pd.options.display.float_format = '{:,.2f}'.format

[TJN TOOLS: Data processing] Module loaded.
[TJN TOOLS: Other functions] Module loaded.
[TJN TOOLS: Paths] Module loaded. Sharepoint FOUND at /Users/mariocuendagarcia/Library/CloudStorage/OneDrive-SharedLibraries-TaxJusticeNetworkLtd

## 1. Define the Misalignment Formula

In [2]:
def calculate_misalignment(cbcr_data,
                           formula_vars=['n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",
                                         'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip'],
                           weights=[.5, 0, 0, .5, 0, 0, 0, 0],
                           profit_var='profit_loss_before_income_tax_corrected',
                           etr_max=0.15): 

    # Create variable with positive profits only for calculating shares
    cbcr_data['profit_var_pos'] = cbcr_data[profit_var]
    cbcr_data.loc[cbcr_data[profit_var] < 0, 'profit_var_pos'] = 0
    cbcr_data['share_profit'] = cbcr_data['profit_var_pos'] / cbcr_data.groupby('iso_parent')['profit_var_pos'].transform('sum')

    # Calculate weighted shares of economic activity
    actual_weights = []
    actual_variables = []
    for i, var in enumerate(formula_vars):
        if var is not None and weights[i] > 0:
            actual_variables.append(f"share_{var}")
            actual_weights.append(weights[i])
            cbcr_data.loc[cbcr_data[var] < 0, var] = 0  # Set economic activity measure to zero if negative
            cbcr_data[f"share_{var}"] = cbcr_data[var] / cbcr_data.groupby('iso_parent')[var].transform('sum')

    # Calculate the share of economic activity
    cbcr_data["share_economy_partner_of_parent"] = (cbcr_data.loc[:, actual_variables] * actual_weights).sum(1, min_count=len(actual_weights))
    # Set economic activity to 1% for those jurisdictions without economic activity but with reported profits
    cbcr_data.loc[(cbcr_data["share_economy_partner_of_parent"] == 0) & (cbcr_data[profit_var] > 0), "share_economy_partner_of_parent"] = 0.01

    # Normalize the economic activity shares to sum to 1
    cbcr_data["share_economy_partner_of_parent"] = cbcr_data["share_economy_partner_of_parent"] / cbcr_data.groupby('iso_parent')["share_economy_partner_of_parent"].transform('sum')

    # Calculate theoretical profit and misaligned profit
    cbcr_data["theoretical_profit"] = cbcr_data["share_economy_partner_of_parent"] * cbcr_data.groupby('iso_parent')[profit_var].transform('sum')
    cbcr_data["misaligned_profit"] = cbcr_data[profit_var] - cbcr_data["theoretical_profit"]

    # Set positive misaligned profits to 0 if ETR exceeds the threshold (etr_max)
    cbcr_data.loc[((cbcr_data["misaligned_profit"] > 0) & (cbcr_data["etr_average_corrected"] > etr_max)), "misaligned_profit"] = 0

    # Adjust misalignment per 'iso_parent'
    def adjust_misalignment(group):
        total_negative_misalignment = group.loc[group["misaligned_profit"] < 0, "misaligned_profit"].sum()
        total_positive_misalignment = group.loc[group["misaligned_profit"] > 0, "misaligned_profit"].sum()
        
        # Adjust negative misalignments to balance positive misalignments within each 'iso_parent'
        if total_negative_misalignment != 0:
            factor = - total_positive_misalignment / total_negative_misalignment
            group.loc[group["misaligned_profit"] < 0, "misaligned_profit"] *= factor
        
        return group

    # Apply the adjustment by grouping by 'iso_parent'
    cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

    return cbcr_data

## Australia in 2016

In [13]:
# Load the data
final_misalignment_2016 = pd.read_csv(f'{output_tables}/Datasets_to_Perform_Analysis/misalignment_dataset_2016.csv') 

# Start the estimates
misalignment_final_estimates_australia_2016 = final_misalignment_2016[final_misalignment_2016['year'] == 2016].copy()
misalignment_final_estimates_australia_2016 = calculate_misalignment(misalignment_final_estimates_australia_2016, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Generate a new column called negative_misalignment equal to misaligned_profit if misaligned_profit < 0 and a new column called positive_misalignment equal to misaligned_profit if misaligned_profit > 0
misalignment_final_estimates_australia_2016['negative_misalignment'] = misalignment_final_estimates_australia_2016['misaligned_profit'].apply(lambda x: x if x < 0 else 0)
misalignment_final_estimates_australia_2016['positive_misalignment'] = misalignment_final_estimates_australia_2016['misaligned_profit'].apply(lambda x: x if x > 0 else 0)

# Rename profit_loss_before_income_tax_corrected to reported_profit
misalignment_final_estimates_australia_2016 = misalignment_final_estimates_australia_2016.rename(columns={'profit_loss_before_income_tax_corrected': 'reported_profit'})

# Convert results to millions
misalignment_final_estimates_australia_2016['negative_misalignment'] = -misalignment_final_estimates_australia_2016['negative_misalignment'] / 1e6
misalignment_final_estimates_australia_2016['positive_misalignment'] = misalignment_final_estimates_australia_2016['positive_misalignment'] / 1e6
misalignment_final_estimates_australia_2016['theoretical_profit'] = misalignment_final_estimates_australia_2016['theoretical_profit'] / 1e6
misalignment_final_estimates_australia_2016['reported_profit'] = misalignment_final_estimates_australia_2016['reported_profit'] / 1e6

# Calculate other relevant variables
misalignment_final_estimates_australia_2016['tax_revenue_loss'] = misalignment_final_estimates_australia_2016['negative_misalignment'] * misalignment_final_estimates_australia_2016['cit']
misalignment_final_estimates_australia_2016['tax_revenue_gain'] = misalignment_final_estimates_australia_2016['positive_misalignment'] * misalignment_final_estimates_australia_2016['etr_average_corrected']

# Keep iso_partner, iso_parent, year, negative_misalignment, positive_misalignment, tax_revenue_loss, tax_revenue gain
misalignment_final_estimates_australia_2016 = misalignment_final_estimates_australia_2016[['iso_parent', 'iso_partner', 'year', 'cit', 'theoretical_profit', 'reported_profit', 'negative_misalignment', 'positive_misalignment', 'tax_revenue_loss', 'tax_revenue_gain']]

# Sort by iso_partner and then iso_parent
misalignment_final_estimates_australia_2016 = misalignment_final_estimates_australia_2016.sort_values(by=['iso_parent', 'iso_partner'])   

# Display 8 decimals
pd.options.display.float_format = '{:,.8f}'.format
pd.set_option('display.max_rows', None)
misalignment_final_estimates_australia_2016[(misalignment_final_estimates_australia_2016['iso_parent'] == 'AUS')] #| (misalignment_final_estimates_australia_2016['iso_partner'] == 'AUS')]

/var/folders/kj/y_rfkb696353czt_6gnx_jkc0000gn/T/ipykernel_7742/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,cit,theoretical_profit,reported_profit,negative_misalignment,positive_misalignment,tax_revenue_loss,tax_revenue_gain
0,AUS,ARE,2016,0.00000000,51.47280536,9.66172799,37.51863043,0.00000000,0.00000000,0.00000000
1,AUS,ARG,2016,0.35000000,41.56116090,72.58364126,-0.00000000,0.00000000,-0.00000000,0.00000000
2,AUS,AUS,2016,0.30000000,"45,783.25704388","43,361.75250940","2,172.90582893",0.00000000,651.87174868,0.00000000
3,AUS,AUT,2016,0.25000000,6.22629002,5.86374104,0.32532865,0.00000000,0.08133216,0.00000000
4,AUS,BEL,2016,0.33990000,59.80166833,70.33835017,-0.00000000,0.00000000,-0.00000000,0.00000000
5,AUS,BMU,2016,0.00000000,1.62304933,159.35905649,-0.00000000,157.73600716,-0.00000000,1.76610375
6,AUS,BRA,2016,0.34000000,80.39614786,-246.60125210,293.42689485,0.00000000,99.76514425,0.00000000
7,AUS,CAN,2016,0.26700000,402.06291084,31.79837777,332.25209811,0.00000000,88.71131019,0.00000000
8,AUS,CHE,2016,0.21148581,243.48242433,"1,135.91157953",-0.00000000,892.42915520,-0.00000000,78.47174200
9,AUS,CHL,2016,0.24000000,561.10419902,727.28969490,-0.00000000,0.00000000,-0.00000000,0.00000000
10,AUS,CHN,2016,0.25000000,391.19820113,124.06952120,239.70447192,0.00000000,59.92611798,0.00000000
11,AUS,COL,2016,0.40000000,47.77791719,-31.48061394,71.12161957,0.00000000,28.44864783,0.00000000
12,AUS,CYM,2016,0.00000000,594.81283939,322.95388516,243.94912249,0.00000000,0.00000000,0.00000000
13,AUS,CZE,2016,0.19000000,6.59203272,9.94715060,-0.00000000,3.35511788,-0.00000000,0.46720337
14,AUS,DEU,2016,0.29818844,440.99887086,"1,582.09868300",-0.00000000,"1,141.09981214",-0.00000000,159.30499161
15,AUS,DNK,2016,0.22000000,17.00940168,72.98452855,-0.00000000,55.97512687,-0.00000000,6.19307764
16,AUS,ECU,2016,0.22000000,14.94610820,28.88439184,-0.00000000,0.00000000,-0.00000000,0.00000000
17,AUS,ESP,2016,0.25000000,49.20161643,24.90897866,21.79868485,0.00000000,5.44967121,0.00000000
18,AUS,FIN,2016,0.20000000,12.10246800,-2.55740309,13.15484604,0.00000000,2.63096921,0.00000000
19,AUS,FJI,2016,0.20000000,22.72767094,18.24057829,4.02643465,0.00000000,0.80528693,0.00000000
20,AUS,FRA,2016,0.34433333,965.27023963,281.76185490,613.33742397,0.00000000,211.19251761,0.00000000
21,AUS,GBR,2016,0.20000000,"1,559.18504094","8,032.46859900",-0.00000000,"6,473.28355806",-0.00000000,588.78153124
22,AUS,GGY,2016,0.00000000,594.81283939,60.74129725,479.24220271,0.00000000,0.00000000,0.00000000
23,AUS,HKG,2016,0.16500000,116.61200751,180.63563309,-0.00000000,64.02362558,-0.00000000,5.06800284
24,AUS,IDN,2016,0.25000000,364.42532813,626.50487860,-0.00000000,262.07955047,-0.00000000,-7.44183298
25,AUS,IND,2016,0.47920000,287.99026527,60.31234103,204.30384567,0.00000000,97.90240284,0.00000000
26,AUS,IRL,2016,0.12500000,64.81176704,198.92381636,-0.00000000,134.11204933,-0.00000000,15.30952221
27,AUS,ITA,2016,0.31292750,40.59706830,42.18192017,-0.00000000,0.00000000,-0.00000000,0.00000000
28,AUS,JEY,2016,0.00000000,2.90338022,-21.02471381,21.47156623,0.00000000,0.00000000,0.00000000
29,AUS,JPN,2016,0.29970000,43.26481373,181.63102970,-0.00000000,0.00000000,-0.00000000,0.00000000
30,AUS,KOR,2016,0.24200000,28.64673297,72.37980159,-0.00000000,0.00000000,-0.00000000,0.00000000
31,AUS,LUX,2016,0.29220000,1.53430241,610.60870962,-0.00000000,609.07440721,-0.00000000,14.65242630
32,AUS,MEX,2016,0.30000000,88.87999368,4.48615460,75.72972185,0.00000000,22.71891656,0.00000000
33,AUS,MLT,2016,0.05000000,0.30041314,9.47926084,-0.00000000,9.17884770,-0.00000000,1.10831821
34,AUS,MUS,2016,0.15000000,0.04855223,-186.01569930,166.96235376,0.00000000,25.04435306,0.00000000
35,AUS,MYS,2016,0.24000000,208.53890990,205.03283850,3.14612791,0.00000000,0.75507070,0.00000000
36,AUS,NAM,2016,0.32000000,1.51816103,0.15928582,1.21936912,0.00000000,0.39019812,0.00000000
37,AUS,NLD,2016,0.25000000,51.63545700,-41.01991197,83.14309904,0.00000000,20.78577476,0.00000000
38,AUS,NOR,2016,0.25000000,25.12580944,2.42441069,20.37080706,0.00000000,5.09270177,0.00000000
39,AUS,NZL,2016,0.28000000,"2,503.55211135","3,182.74083100",-0.00000000,0.00000000,-0.00000000,0.00000000
40,AUS,PER,2016,0.28000000,32.82525782,38.40142484,-0.00000000,0.00000000,-0.00000000,0.00000000
41,AUS,PHL,2016,0.30000000,174.78030082,40.14407054,120.81408289,0.00000000,36.24422487,0.00000000
42,AUS,PNG,2016,0.30000000,161.49552603,273.61926070,-0.00000000,112.12373467,-0.00000000,9.76475972
43,AUS,POL,2016,0.19000000,35.84252868,21.43144751,12.93159762,0.00000000,2.45700355,0.00000000
44,AUS,PRT,2016,0.29500000,24.59808850,15.09460919,8.52782446,0.00000000,2.51570822,0.00000000
45,AUS,RUS,2016,0.20000000,23.72248716,66.68530360,-0.00000000,0.00000000,-0.00000000,0.00000000
46,AUS,SGP,2016,0.17000000,291.96188663,"1,369.64819628",-0.00000000,"1,077.68630965",-0.00000000,68.38001526
47,AUS,SLB,2016,0.30000000,2.89215456,3.59144164,-0.00000000,0.69928708,-0.00000000,0.08986000
48,AUS,SWE,2016,0.22000000,23.02547080,12.23503130,9.68266156,0.00000000,2.13018554,0.00000000
49,AUS,THA,2016,0.20000000,204.70338712,78.31104900,113.41653271,0.00000000,22.68330654,0.00000000
50,AUS,TTO,2016,0.25000000,12.69401315,-204.83527770,195.19710053,0.00000000,48.79927513,0.00000000
51,AUS,TUR,2016,0.20000000,29.91148370,20.78581793,8.18879835,0.00000000,1.63775967,0.00000000
52,AUS,TWN,2016,0.17000000,2.88338272,22.01918284,-0.00000000,0.00000000,-0.00000000,0.00000000
53,AUS,USA,2016,0.27000000,"3,433.73490614","-2,611.91681400","5,424.98751306",0.00000000,"1,464.74662852",0.00000000
54,AUS,VNM,2016,0.22000000,73.08939953,119.58454240,-0.00000000,0.00000000,-0.00000000,0.00000000
55,AUS,ZAF,2016,0.28000000,364.74132458,423.69086720,-0.00000000,0.00000000,-0.00000000,0.00000000

In [14]:
# Count how many values in misalignment_final_estimates_australia_2016['iso_parent'] == 'AUS'
misalignment_australia_2016 = misalignment_final_estimates_australia_2016[misalignment_final_estimates_australia_2016['iso_parent'] == 'AUS']

# Count total values in misalignment_australia
misalignment_australia_2016['iso_partner'].count()

# Keep if positive_misalignment > 0
misalignment_australia_2016 = misalignment_australia_2016[misalignment_australia_2016['positive_misalignment'] > 0]
misalignment_australia_2016

# Export the results to excel
misalignment_australia_2016.to_csv(f'{output_tables}/Australia/australia_request_2016.csv', index=False)

## Australia in 2017

In [11]:
# Load the data
final_misalignment_2017 = pd.read_csv(f'{output_tables}/Datasets_to_Perform_Analysis/misalignment_dataset_2017.csv') 

# Start the estimates
misalignment_final_estimates_australia_2017 = final_misalignment_2017[final_misalignment_2017['year'] == 2017].copy()
misalignment_final_estimates_australia_2017 = calculate_misalignment(misalignment_final_estimates_australia_2017, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Generate a new column called negative_misalignment equal to misaligned_profit if misaligned_profit < 0 and a new column called positive_misalignment equal to misaligned_profit if misaligned_profit > 0
misalignment_final_estimates_australia_2017['negative_misalignment'] = misalignment_final_estimates_australia_2017['misaligned_profit'].apply(lambda x: x if x < 0 else 0)
misalignment_final_estimates_australia_2017['positive_misalignment'] = misalignment_final_estimates_australia_2017['misaligned_profit'].apply(lambda x: x if x > 0 else 0)

# Rename profit_loss_before_income_tax_corrected to reported_profit
misalignment_final_estimates_australia_2017 = misalignment_final_estimates_australia_2017.rename(columns={'profit_loss_before_income_tax_corrected': 'reported_profit'})

# Convert results to millions
misalignment_final_estimates_australia_2017['negative_misalignment'] = -misalignment_final_estimates_australia_2017['negative_misalignment'] / 1e6
misalignment_final_estimates_australia_2017['positive_misalignment'] = misalignment_final_estimates_australia_2017['positive_misalignment'] / 1e6
misalignment_final_estimates_australia_2017['theoretical_profit'] = misalignment_final_estimates_australia_2017['theoretical_profit'] / 1e6
misalignment_final_estimates_australia_2017['reported_profit'] = misalignment_final_estimates_australia_2017['reported_profit'] / 1e6

# Calculate other relevant variables
misalignment_final_estimates_australia_2017['tax_revenue_loss'] = misalignment_final_estimates_australia_2017['negative_misalignment'] * misalignment_final_estimates_australia_2017['cit']
misalignment_final_estimates_australia_2017['tax_revenue_gain'] = misalignment_final_estimates_australia_2017['positive_misalignment'] * misalignment_final_estimates_australia_2017['etr_average_corrected']

# Keep iso_partner, iso_parent, year, negative_misalignment, positive_misalignment, tax_revenue_loss, tax_revenue gain
misalignment_final_estimates_australia_2017 = misalignment_final_estimates_australia_2017[['iso_parent', 'iso_partner', 'year', 'cit', 'theoretical_profit', 'reported_profit', 'negative_misalignment', 'positive_misalignment', 'tax_revenue_loss', 'tax_revenue_gain']]

# Sort by iso_partner and then iso_parent
misalignment_final_estimates_australia_2017 = misalignment_final_estimates_australia_2017.sort_values(by=['iso_parent', 'iso_partner'])   

# Display 8 decimals
pd.options.display.float_format = '{:,.8f}'.format
pd.set_option('display.max_rows', None)
misalignment_final_estimates_australia_2017[(misalignment_final_estimates_australia_2017['iso_parent'] == 'AUS')] #| (misalignment_final_estimates_australia_2017['iso_partner'] == 'AUS')]

/var/folders/kj/y_rfkb696353czt_6gnx_jkc0000gn/T/ipykernel_7742/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,cit,theoretical_profit,reported_profit,negative_misalignment,positive_misalignment,tax_revenue_loss,tax_revenue_gain
15,AUS,ARE,2017,0.00000000,64.75702417,9.50827241,40.25891238,0.00000000,0.00000000,0.00000000
16,AUS,ARG,2017,0.35000000,56.13390061,55.62791700,0.36870244,0.00000000,0.12904586,0.00000000
17,AUS,AUS,2017,0.30000000,"58,603.32513598","57,758.07272235",615.92238337,0.00000000,184.77671501,0.00000000
18,AUS,AUT,2017,0.25000000,16.34780060,15.15843000,0.86667599,0.00000000,0.21666900,0.00000000
19,AUS,BEL,2017,0.33990000,76.94101145,93.35817200,-0.00000000,0.00000000,-0.00000000,0.00000000
20,AUS,BGR,2017,0.10000000,4.42091124,2.51819400,1.38648068,0.00000000,0.13864807,0.00000000
21,AUS,BMU,2017,0.00000000,1.83588500,-478.23357800,349.81920556,0.00000000,0.00000000,0.00000000
22,AUS,BRA,2017,0.34000000,127.59448450,-223.35896600,255.73436076,0.00000000,86.94968266,0.00000000
23,AUS,CAN,2017,0.26650000,559.67508232,137.72225100,307.47051336,0.00000000,81.94089181,0.00000000
24,AUS,CHE,2017,0.21148581,264.05260632,"1,142.59185222",-0.00000000,878.53924590,-0.00000000,70.66608709
25,AUS,CHL,2017,0.25500000,727.33883573,739.61319900,-0.00000000,0.00000000,-0.00000000,0.00000000
26,AUS,CHN,2017,0.25000000,524.49450354,183.09197900,248.77474848,0.00000000,62.19368712,0.00000000
27,AUS,COL,2017,0.40000000,62.36726336,-45.92593000,78.91157799,0.00000000,31.56463119,0.00000000
28,AUS,CYM,2017,0.00000000,769.79918684,323.02180729,325.55977837,0.00000000,0.00000000,0.00000000
29,AUS,CYP,2017,0.12500000,0.00000000,-0.15725200,0.11458710,0.00000000,0.01432339,0.00000000
30,AUS,CZE,2017,0.19000000,9.87748254,10.17941300,-0.00000000,0.30193046,-0.00000000,0.04319925
31,AUS,DEU,2017,0.29889263,558.66383202,"1,523.45630800",-0.00000000,964.79247598,-0.00000000,131.90008366
32,AUS,DNK,2017,0.22000000,20.67560144,72.24960900,-0.00000000,51.57400756,-0.00000000,5.99050932
33,AUS,ECU,2017,0.22000000,16.23513949,12.40856700,2.78836429,0.00000000,0.61344014,0.00000000
34,AUS,EGY,2017,0.22500000,1.59551280,0.71430800,0.64212033,0.00000000,0.14447708,0.00000000
35,AUS,ESP,2017,0.25000000,84.76724302,60.78382800,17.47634423,0.00000000,4.36908606,0.00000000
36,AUS,FIN,2017,0.20000000,14.52991718,-1.99458700,12.04115106,0.00000000,2.40823021,0.00000000
37,AUS,FJI,2017,0.20000000,60.58118310,95.46107600,-0.00000000,0.00000000,-0.00000000,0.00000000
38,AUS,FRA,2017,0.44433333,"1,173.86713820",308.88278100,630.30074600,0.00000000,280.06362937,0.00000000
39,AUS,GBR,2017,0.19000000,"1,939.04433866","7,857.65293700",-0.00000000,"5,918.60859834",-0.00000000,494.18967122
40,AUS,GGY,2017,0.00000000,769.79918684,60.80485138,516.63322559,0.00000000,0.00000000,0.00000000
41,AUS,GHA,2017,0.25000000,1.90458844,2.20584500,-0.00000000,0.00000000,-0.00000000,0.00000000
42,AUS,GRC,2017,0.29000000,2.84315898,2.29139100,0.40206481,0.00000000,0.11659879,0.00000000
43,AUS,HKG,2017,0.16500000,161.08776643,174.51618457,-0.00000000,13.42841814,-0.00000000,0.99932729
44,AUS,HUN,2017,0.09000000,3.25976823,1.25342672,1.46199008,0.00000000,0.13157911,0.00000000
45,AUS,IDN,2017,0.25000000,487.87486299,539.56063700,-0.00000000,51.68577401,-0.00000000,-1.46763415
46,AUS,IND,2017,0.47920000,526.04454237,123.94905700,293.00077196,0.00000000,140.40596992,0.00000000
47,AUS,IRL,2017,0.12500000,82.93308915,184.41376135,-0.00000000,101.48067220,-0.00000000,12.35594624
48,AUS,ITA,2017,0.27806400,49.02216616,60.25121000,-0.00000000,0.00000000,-0.00000000,0.00000000
49,AUS,JEY,2017,0.00000000,3.45199645,-33.81259600,27.15413316,0.00000000,0.00000000,0.00000000
50,AUS,JPN,2017,0.29970000,46.36683247,252.88319100,-0.00000000,0.00000000,-0.00000000,0.00000000
51,AUS,KAZ,2017,0.20000000,30.62324101,8.23591700,16.31329735,0.00000000,3.26265947,0.00000000
52,AUS,KOR,2017,0.24200000,42.65447790,80.29360000,-0.00000000,0.00000000,-0.00000000,0.00000000
53,AUS,LUX,2017,0.27080000,1.88393052,104.52735293,-0.00000000,102.64342241,-0.00000000,2.64058272
54,AUS,MAR,2017,0.31000000,5.47667720,-4.11588700,6.98995343,0.00000000,2.16688556,0.00000000
55,AUS,MEX,2017,0.30000000,140.80657850,14.38594800,92.12076155,0.00000000,27.63622846,0.00000000
56,AUS,MLT,2017,0.05000000,0.36319122,9.77093026,-0.00000000,9.40773904,-0.00000000,1.18722104
57,AUS,MMR,2017,0.25000000,8.76839200,-39.32024600,35.04144804,0.00000000,8.76036201,0.00000000
58,AUS,MOZ,2017,0.32000000,27.90172716,42.87487600,-0.00000000,0.00000000,-0.00000000,0.00000000
59,AUS,MUS,2017,0.15000000,0.05728614,0.35447321,-0.00000000,0.29718707,-0.00000000,0.01137964
60,AUS,MYS,2017,0.24000000,227.48645761,109.04526100,86.30627127,0.00000000,20.71350510,0.00000000
61,AUS,NAM,2017,0.32000000,0.69769043,-0.08673000,0.57159506,0.00000000,0.18291042,0.00000000
62,AUS,NCL,2017,0.00000000,3.68647778,10.04468900,-0.00000000,0.00000000,-0.00000000,0.00000000
63,AUS,NLD,2017,0.25000000,50.55876146,64.13085861,-0.00000000,13.57209715,-0.00000000,1.02099694
64,AUS,NOR,2017,0.24000000,37.60829475,-282.56800400,233.30752547,0.00000000,55.99380611,0.00000000
65,AUS,NZL,2017,0.28000000,"3,856.93553322","7,113.59209500",-0.00000000,0.00000000,-0.00000000,0.00000000
66,AUS,PAN,2017,0.25000000,2.36051037,9.15976000,-0.00000000,6.79924963,-0.00000000,0.54128444
67,AUS,PER,2017,0.29500000,50.85725382,35.01962200,11.54063778,0.00000000,3.40448814,0.00000000
68,AUS,PHL,2017,0.30000000,367.36306444,92.49208200,200.29424098,0.00000000,60.08827229,0.00000000
69,AUS,PNG,2017,0.30000000,246.39374852,"1,084.12860900",-0.00000000,837.73486048,-0.00000000,84.32438847
70,AUS,POL,2017,0.19000000,54.01943245,19.59503700,25.08452546,0.00000000,4.76605984,0.00000000
71,AUS,PRT,2017,0.29500000,31.14218504,15.81644500,11.16763014,0.00000000,3.29445089,0.00000000
72,AUS,ROU,2017,0.16000000,1.11270395,1.08385400,0.02102251,0.00000000,0.00336360,0.00000000
73,AUS,RUS,2017,0.20000000,38.84408282,65.38566700,-0.00000000,0.00000000,-0.00000000,0.00000000
74,AUS,SGP,2017,0.17000000,373.71082473,"1,494.14076448",-0.00000000,"1,120.42993975",-0.00000000,72.59336795
75,AUS,SLB,2017,0.30000000,5.74715469,5.73147400,0.01142628,0.00000000,0.00342788,0.00000000
76,AUS,SVK,2017,0.21000000,0.13199392,1.59258500,-0.00000000,1.46059108,-0.00000000,0.18001949
77,AUS,SWE,2017,0.22000000,49.03433622,34.89698100,10.30167247,0.00000000,2.26636794,0.00000000
78,AUS,THA,2017,0.20000000,194.71251715,76.26198200,86.31307612,0.00000000,17.26261522,0.00000000
79,AUS,TLS,2017,0.10000000,5.37050944,31.40538700,-0.00000000,26.03487756,-0.00000000,3.13224280
80,AUS,TTO,2017,0.30000000,14.84725171,-204.87368100,160.10725124,0.00000000,48.03217537,0.00000000
81,AUS,TUR,2017,0.20000000,49.87284056,43.04731600,4.97365437,0.00000000,0.99473087,0.00000000
82,AUS,TWN,2017,0.17000000,41.47068853,63.28979400,-0.00000000,0.00000000,-0.00000000,0.00000000
83,AUS,TZA,2017,0.30000000,3.56833406,1.47316900,1.52671443,0.00000000,0.45801433,0.00000000
84,AUS,USA,2017,0.27000000,"4,243.93769293","-2,518.14126200","4,927.42253000",0.00000000,"1,330.40408310",0.00000000
85,AUS,VEN,2017,0.34000000,15.30746492,-5.13401200,14.89538862,0.00000000,5.06443213,0.00000000
86,AUS,VGB,2017,0.00000000,769.79918684,2.71592503,558.96172935,0.00000000,0.00000000,0.00000000
87,AUS,VNM,2017,0.20000000,83.73441876,107.18236900,-0.00000000,0.00000000,-0.00000000,0.00000000
88,AUS,VUT,2017,0.00000000,5.35783741,7.32182900,-0.00000000,1.96399159,-0.00000000,0.00000000
89,AUS,ZAF,2017,0.28000000,329.25961259,461.89013000,-0.00000000,0.00000000,-0.00000000,0.00000000
90,AUS,ZMB,2017,0.35000000,2.34290338,111.94901500,-0.00000000,109.60611162,-0.00000000,15.18622057

In [12]:
# Count how many values in misalignment_final_estimates_australia_2017['iso_parent'] == 'AUS'
misalignment_australia_2017 = misalignment_final_estimates_australia_2017[misalignment_final_estimates_australia_2017['iso_parent'] == 'AUS']

# Count total values in misalignment_australia
misalignment_australia_2017['iso_partner'].count()

# Keep if positive_misalignment > 0
misalignment_australia_2017 = misalignment_australia_2017[misalignment_australia_2017['positive_misalignment'] > 0]
misalignment_australia_2017

# Export the results to excel
misalignment_australia_2017.to_csv(f'{output_tables}/Australia/australia_request_2017.csv', index=False)

## Australia in 2018

In [9]:
# Load the data
final_misalignment_2018 = pd.read_csv(f'{output_tables}/Datasets_to_Perform_Analysis/misalignment_dataset_2018.csv') 

# Start the estimates
misalignment_final_estimates_australia_2018 = final_misalignment_2018[final_misalignment_2018['year'] == 2018].copy()
misalignment_final_estimates_australia_2018 = calculate_misalignment(misalignment_final_estimates_australia_2018, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Generate a new column called negative_misalignment equal to misaligned_profit if misaligned_profit < 0 and a new column called positive_misalignment equal to misaligned_profit if misaligned_profit > 0
misalignment_final_estimates_australia_2018['negative_misalignment'] = misalignment_final_estimates_australia_2018['misaligned_profit'].apply(lambda x: x if x < 0 else 0)
misalignment_final_estimates_australia_2018['positive_misalignment'] = misalignment_final_estimates_australia_2018['misaligned_profit'].apply(lambda x: x if x > 0 else 0)

# Rename profit_loss_before_income_tax_corrected to reported_profit
misalignment_final_estimates_australia_2018 = misalignment_final_estimates_australia_2018.rename(columns={'profit_loss_before_income_tax_corrected': 'reported_profit'})

# Convert results to millions
misalignment_final_estimates_australia_2018['negative_misalignment'] = -misalignment_final_estimates_australia_2018['negative_misalignment'] / 1e6
misalignment_final_estimates_australia_2018['positive_misalignment'] = misalignment_final_estimates_australia_2018['positive_misalignment'] / 1e6
misalignment_final_estimates_australia_2018['theoretical_profit'] = misalignment_final_estimates_australia_2018['theoretical_profit'] / 1e6
misalignment_final_estimates_australia_2018['reported_profit'] = misalignment_final_estimates_australia_2018['reported_profit'] / 1e6

# Calculate other relevant variables
misalignment_final_estimates_australia_2018['tax_revenue_loss'] = misalignment_final_estimates_australia_2018['negative_misalignment'] * misalignment_final_estimates_australia_2018['cit']
misalignment_final_estimates_australia_2018['tax_revenue_gain'] = misalignment_final_estimates_australia_2018['positive_misalignment'] * misalignment_final_estimates_australia_2018['etr_average_corrected']

# Keep iso_partner, iso_parent, year, negative_misalignment, positive_misalignment, tax_revenue_loss, tax_revenue gain
misalignment_final_estimates_australia_2018 = misalignment_final_estimates_australia_2018[['iso_parent', 'iso_partner', 'year', 'cit', 'theoretical_profit', 'reported_profit', 'negative_misalignment', 'positive_misalignment', 'tax_revenue_loss', 'tax_revenue_gain']]

# Sort by iso_partner and then iso_parent
misalignment_final_estimates_australia_2018 = misalignment_final_estimates_australia_2018.sort_values(by=['iso_parent', 'iso_partner'])   

# Display 8 decimals
pd.options.display.float_format = '{:,.8f}'.format
pd.set_option('display.max_rows', None)
misalignment_final_estimates_australia_2018[(misalignment_final_estimates_australia_2018['iso_parent'] == 'AUS')] #| (misalignment_final_estimates_australia_2018['iso_partner'] == 'AUS')]

/var/folders/kj/y_rfkb696353czt_6gnx_jkc0000gn/T/ipykernel_7742/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,cit,theoretical_profit,reported_profit,negative_misalignment,positive_misalignment,tax_revenue_loss,tax_revenue_gain
19,AUS,ARE,2018,0.00000000,20.81821725,9.27104997,6.18094742,0.00000000,0.00000000,0.00000000
20,AUS,ARG,2018,0.30000000,39.11772964,25.64693800,7.21062169,0.00000000,2.16318651,0.00000000
21,AUS,AUS,2018,0.30000000,"69,234.72606312","58,131.80672975","5,943.15115727",0.00000000,"1,782.94534718",0.00000000
22,AUS,AUT,2018,0.25000000,17.28733549,19.03805500,-0.00000000,1.75071951,-0.00000000,0.17363673
23,AUS,BEL,2018,0.29580000,84.34460437,135.85460300,-0.00000000,0.00000000,-0.00000000,0.00000000
24,AUS,BGR,2018,0.10000000,3.95739059,3.29226900,0.35602512,0.00000000,0.03560251,0.00000000
25,AUS,BMU,2018,0.00000000,2.09081366,332.33614050,-0.00000000,330.24532684,-0.00000000,4.40443229
26,AUS,BRA,2018,0.34000000,161.79142816,-437.41080900,320.73992094,0.00000000,109.05157312,0.00000000
27,AUS,BWA,2018,0.22000000,0.03070341,2.01189200,-0.00000000,0.00000000,-0.00000000,0.00000000
28,AUS,CAN,2018,0.26780000,658.65267238,465.37668000,103.45643369,0.00000000,27.70563294,0.00000000
29,AUS,CHE,2018,0.21148581,312.82067660,"1,858.57717227",-0.00000000,"1,545.75649567",-0.00000000,114.93738359
30,AUS,CHL,2018,0.27000000,734.80206591,"3,810.42038100",-0.00000000,0.00000000,-0.00000000,0.00000000
31,AUS,CHN,2018,0.25000000,594.59365722,299.03317700,158.20709467,0.00000000,39.55177367,0.00000000
32,AUS,COL,2018,0.37000000,68.09063610,104.66849000,-0.00000000,0.00000000,-0.00000000,0.00000000
33,AUS,CRI,2018,0.30000000,0.56682143,0.95805100,-0.00000000,0.39122957,-0.00000000,0.05165668
34,AUS,CYM,2018,0.00000000,0.21385518,536.79552927,-0.00000000,536.58167409,-0.00000000,2.96763691
35,AUS,CZE,2018,0.19000000,35.82102051,14.76930900,11.26852316,0.00000000,2.14101940,0.00000000
36,AUS,DEU,2018,0.29897059,674.96268116,"1,447.53079000",-0.00000000,772.56810884,-0.00000000,108.44104342
37,AUS,DNK,2018,0.22000000,27.36944797,50.58939700,-0.00000000,23.21994903,-0.00000000,2.70560655
38,AUS,DOM,2018,0.27000000,4.82579446,6.78200200,-0.00000000,0.00000000,-0.00000000,0.00000000
39,AUS,ECU,2018,0.25000000,3.18705454,-14.02347200,9.21242042,0.00000000,2.30310510,0.00000000
40,AUS,EGY,2018,0.22500000,2.13405333,-0.05086300,1.16953817,0.00000000,0.26314609,0.00000000
41,AUS,ESP,2018,0.25000000,65.83917992,75.49251800,-0.00000000,9.65333808,-0.00000000,1.10685350
42,AUS,FIN,2018,0.20000000,17.61446355,-1.10301700,10.01906011,0.00000000,2.00381202,0.00000000
43,AUS,FJI,2018,0.20000000,64.55145526,22.46334100,22.52885187,0.00000000,4.50577037,0.00000000
44,AUS,FRA,2018,0.34433333,"1,307.52399699",267.89621400,556.49013346,0.00000000,191.61810077,0.00000000
45,AUS,GBR,2018,0.19000000,"1,671.03196536","5,476.77192500",-0.00000000,"3,805.73995964",-0.00000000,368.84136556
46,AUS,GGY,2018,0.00000000,890.01706931,98.56794311,423.64549801,0.00000000,0.00000000,0.00000000
47,AUS,GHA,2018,0.25000000,4.36986599,2.10276900,1.21352769,0.00000000,0.30338192,0.00000000
48,AUS,HKG,2018,0.16500000,176.49624094,464.30464353,-0.00000000,287.80840259,-0.00000000,21.30402188
49,AUS,HUN,2018,0.09000000,4.30078335,4.67719434,-0.00000000,0.37641099,-0.00000000,0.03798455
50,AUS,IDN,2018,0.25000000,475.14856814,439.48144600,19.09183448,0.00000000,4.77295862,-0.00000000
51,AUS,IND,2018,0.48320000,585.56260404,142.45898300,237.18372791,0.00000000,114.60717733,0.00000000
52,AUS,IRL,2018,0.12500000,39.50367814,149.96852871,-0.00000000,110.46485057,-0.00000000,12.70050203
53,AUS,ITA,2018,0.27806400,55.56902611,70.85199600,-0.00000000,0.00000000,-0.00000000,0.00000000
54,AUS,JEY,2018,0.00000000,3.36014683,20.20243134,-0.00000000,16.84228451,-0.00000000,0.08009834
55,AUS,JPN,2018,0.29740000,177.87464282,211.66339500,-0.00000000,0.00000000,-0.00000000,0.00000000
56,AUS,KAZ,2018,0.20000000,38.49045941,24.02360200,7.74379402,0.00000000,1.54875880,0.00000000
57,AUS,KOR,2018,0.27500000,44.42745474,55.76394500,-0.00000000,0.00000000,-0.00000000,0.00000000
58,AUS,LUX,2018,0.26010000,2.07277895,185.97029269,-0.00000000,183.89751374,-0.00000000,4.95105326
59,AUS,MAR,2018,0.31000000,5.49306901,-20.63190800,13.98413180,0.00000000,4.33508086,0.00000000
60,AUS,MEX,2018,0.30000000,150.30703370,-94.78558400,131.19274587,0.00000000,39.35782376,0.00000000
61,AUS,MLT,2018,0.05000000,0.44684479,-5.89841000,3.39647684,0.00000000,0.16982384,0.00000000
62,AUS,MMR,2018,0.25000000,13.07324331,-33.22494000,24.78241023,0.00000000,6.19560256,0.00000000
63,AUS,MOZ,2018,0.32000000,32.51481452,67.06718500,-0.00000000,0.00000000,-0.00000000,0.00000000
64,AUS,MUS,2018,0.15000000,0.06373625,51.40260307,-0.00000000,51.33886682,-0.00000000,1.45459840
65,AUS,MYS,2018,0.24000000,282.33238920,153.04240900,69.20611349,0.00000000,16.60946724,0.00000000
66,AUS,NAM,2018,0.32000000,2.43085108,1.00466500,0.76340638,0.00000000,0.24429004,0.00000000
67,AUS,NCL,2018,0.00000000,3.97653186,8.37254700,-0.00000000,0.00000000,-0.00000000,0.00000000
68,AUS,NLD,2018,0.25000000,61.07213619,31.10214380,16.04228488,0.00000000,4.01057122,0.00000000
69,AUS,NOR,2018,0.23000000,58.25527143,-30.53699100,47.52856626,0.00000000,10.93157024,0.00000000
70,AUS,NZL,2018,0.28000000,"4,223.93474171","6,525.61576400",-0.00000000,0.00000000,-0.00000000,0.00000000
71,AUS,PAN,2018,0.25000000,2.93418894,6.72339600,-0.00000000,3.78920706,-0.00000000,0.27648141
72,AUS,PER,2018,0.29500000,59.51849717,1.59818000,31.00348563,0.00000000,9.14602826,0.00000000
73,AUS,PHL,2018,0.30000000,323.53037373,67.74861900,136.91440836,0.00000000,41.07432251,0.00000000
74,AUS,PNG,2018,0.30000000,263.32457633,730.35355700,-0.00000000,467.02898067,-0.00000000,48.54609807
75,AUS,POL,2018,0.19000000,63.72016718,64.69749700,-0.00000000,0.00000000,-0.00000000,0.00000000
76,AUS,PRT,2018,0.31500000,41.15401920,26.48029300,7.85452638,0.00000000,2.47417581,0.00000000
77,AUS,ROU,2018,0.16000000,4.20639667,0.73049600,1.86057400,0.00000000,0.29769184,0.00000000
78,AUS,RUS,2018,0.20000000,62.98116798,66.01407500,-0.00000000,0.00000000,-0.00000000,0.00000000
79,AUS,SGP,2018,0.17000000,390.65605228,"1,187.70916082",-0.00000000,797.05310854,-0.00000000,52.21134156
80,AUS,SLB,2018,0.30000000,7.27529016,13.32046600,-0.00000000,6.04517584,-0.00000000,0.79456901
81,AUS,SVK,2018,0.21000000,1.33270373,-0.28145000,0.86402137,0.00000000,0.18144449,0.00000000
82,AUS,SWE,2018,0.22000000,62.49268030,23.01425800,21.13194054,0.00000000,4.64902692,0.00000000
83,AUS,THA,2018,0.20000000,251.60398446,86.43643300,88.41059681,0.00000000,17.68211936,0.00000000
84,AUS,TLS,2018,0.10000000,6.85996084,84.32746900,-0.00000000,77.46750816,-0.00000000,8.10890748
85,AUS,TTO,2018,0.30000000,36.17292893,-144.19726400,96.54824003,0.00000000,28.96447201,0.00000000
86,AUS,TUR,2018,0.22000000,33.39918264,13.93701000,10.41767758,0.00000000,2.29188907,0.00000000
87,AUS,TWN,2018,0.20000000,10.94314046,61.64886800,-0.00000000,0.00000000,-0.00000000,0.00000000
88,AUS,TZA,2018,0.30000000,3.23783334,-1.44992400,2.50925451,0.00000000,0.75277635,0.00000000
89,AUS,UKR,2018,0.18000000,24.94785385,6.79608500,9.71624694,0.00000000,1.74892445,0.00000000
90,AUS,USA,2018,0.27000000,"4,568.27490742","6,676.82491900",-0.00000000,0.00000000,-0.00000000,0.00000000
91,AUS,VGB,2018,0.00000000,890.01706931,2.45045983,475.09509562,0.00000000,0.00000000,0.00000000
92,AUS,VNM,2018,0.20000000,92.24179692,189.83192700,-0.00000000,0.00000000,-0.00000000,0.00000000
93,AUS,VUT,2018,0.00000000,4.74739774,9.51071500,-0.00000000,4.76331726,-0.00000000,0.00000000
94,AUS,ZAF,2018,0.28000000,432.39011786,444.99954100,-0.00000000,0.00000000,-0.00000000,0.00000000
95,AUS,ZMB,2018,0.35000000,3.91901722,-4.84486300,4.69111441,0.00000000,1.64189004,0.00000000

In [ ]:
# Count how many values in misalignment_final_estimates_australia_2018['iso_parent'] == 'AUS'
misalignment_australia_2018 = misalignment_final_estimates_australia_2018[misalignment_final_estimates_australia_2018['iso_parent'] == 'AUS']

# Count total values in misalignment_australia
misalignment_australia_2018['iso_partner'].count()

# Keep if positive_misalignment > 0
misalignment_australia_2018 = misalignment_australia_2018[misalignment_australia_2018['positive_misalignment'] > 0]
misalignment_australia_2018

# Export the results to excel
misalignment_australia_2018.to_csv(f'{output_tables}/Australia/australia_request_2018.csv', index=False)

## Australia in 2019

In [7]:
# Load the data
final_misalignment_2019 = pd.read_csv(f'{output_tables}/Datasets_to_Perform_Analysis/misalignment_dataset_2019.csv') 

# Start the estimates
misalignment_final_estimates_australia_2019 = final_misalignment_2019[final_misalignment_2019['year'] == 2019].copy()
misalignment_final_estimates_australia_2019 = calculate_misalignment(misalignment_final_estimates_australia_2019, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Generate a new column called negative_misalignment equal to misaligned_profit if misaligned_profit < 0 and a new column called positive_misalignment equal to misaligned_profit if misaligned_profit > 0
misalignment_final_estimates_australia_2019['negative_misalignment'] = misalignment_final_estimates_australia_2019['misaligned_profit'].apply(lambda x: x if x < 0 else 0)
misalignment_final_estimates_australia_2019['positive_misalignment'] = misalignment_final_estimates_australia_2019['misaligned_profit'].apply(lambda x: x if x > 0 else 0)

# Rename profit_loss_before_income_tax_corrected to reported_profit
misalignment_final_estimates_australia_2019 = misalignment_final_estimates_australia_2019.rename(columns={'profit_loss_before_income_tax_corrected': 'reported_profit'})

# Convert results to millions
misalignment_final_estimates_australia_2019['negative_misalignment'] = -misalignment_final_estimates_australia_2019['negative_misalignment'] / 1e6
misalignment_final_estimates_australia_2019['positive_misalignment'] = misalignment_final_estimates_australia_2019['positive_misalignment'] / 1e6
misalignment_final_estimates_australia_2019['theoretical_profit'] = misalignment_final_estimates_australia_2019['theoretical_profit'] / 1e6
misalignment_final_estimates_australia_2019['reported_profit'] = misalignment_final_estimates_australia_2019['reported_profit'] / 1e6

# Calculate other relevant variables
misalignment_final_estimates_australia_2019['tax_revenue_loss'] = misalignment_final_estimates_australia_2019['negative_misalignment'] * misalignment_final_estimates_australia_2019['cit']
misalignment_final_estimates_australia_2019['tax_revenue_gain'] = misalignment_final_estimates_australia_2019['positive_misalignment'] * misalignment_final_estimates_australia_2019['etr_average_corrected']

# Keep iso_partner, iso_parent, year, negative_misalignment, positive_misalignment, tax_revenue_loss, tax_revenue gain
misalignment_final_estimates_australia_2019 = misalignment_final_estimates_australia_2019[['iso_parent', 'iso_partner', 'year', 'cit', 'theoretical_profit', 'reported_profit', 'negative_misalignment', 'positive_misalignment', 'tax_revenue_loss', 'tax_revenue_gain']]

# Sort by iso_partner and then iso_parent
misalignment_final_estimates_australia_2019 = misalignment_final_estimates_australia_2019.sort_values(by=['iso_parent', 'iso_partner'])   

# Display 8 decimals
pd.options.display.float_format = '{:,.8f}'.format
pd.set_option('display.max_rows', None)
misalignment_final_estimates_australia_2019[(misalignment_final_estimates_australia_2019['iso_parent'] == 'AUS')] #| (misalignment_final_estimates_australia_2019['iso_partner'] == 'AUS')]

/var/folders/kj/y_rfkb696353czt_6gnx_jkc0000gn/T/ipykernel_7742/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,cit,theoretical_profit,reported_profit,negative_misalignment,positive_misalignment,tax_revenue_loss,tax_revenue_gain
18,AUS,ARE,2019,0.00000000,56.40537971,23.10542900,22.27619285,0.00000000,0.00000000,0.00000000
19,AUS,ARG,2019,0.30000000,27.43558313,6.11199000,14.26453982,0.00000000,4.27936195,0.00000000
20,AUS,AUS,2019,0.30000000,"53,968.78810774","53,840.68670500",85.69416745,0.00000000,25.70825024,0.00000000
21,AUS,AUT,2019,0.25000000,17.22347935,24.17682300,-0.00000000,6.95334365,-0.00000000,0.67001975
22,AUS,BEL,2019,0.29580000,125.11986445,66.98999900,38.88630660,0.00000000,11.50256949,0.00000000
23,AUS,BGR,2019,0.10000000,5.31355236,-24.55420400,19.98020677,0.00000000,1.99802068,0.00000000
24,AUS,BMU,2019,0.00000000,1.85393265,308.98186100,-0.00000000,307.12792835,-0.00000000,3.83247428
25,AUS,BRA,2019,0.34000000,121.24026773,38.34814300,55.45116185,0.00000000,18.85339503,0.00000000
26,AUS,BWA,2019,0.22000000,0.67866017,2.38632800,-0.00000000,0.00000000,-0.00000000,0.00000000
27,AUS,CAN,2019,0.26620000,866.63521880,-528.79439200,933.48063466,0.00000000,248.49254495,0.00000000
28,AUS,CHE,2019,0.21148581,252.00522405,"1,638.44535000",-0.00000000,"1,386.44012595",-0.00000000,104.37570511
29,AUS,CHL,2019,0.27000000,"1,023.03105353","2,490.45841700",-0.00000000,0.00000000,-0.00000000,0.00000000
30,AUS,CHN,2019,0.25000000,469.70271278,218.87223000,167.79448884,0.00000000,41.94862221,0.00000000
31,AUS,COL,2019,0.33000000,54.58370593,34.61908600,13.35544691,0.00000000,4.40729748,0.00000000
32,AUS,CYM,2019,0.00000000,0.22704484,563.85127400,-0.00000000,563.62422916,-0.00000000,2.82518715
33,AUS,CYP,2019,0.12500000,1.49117950,4.24536300,-0.00000000,2.75418350,-0.00000000,0.06510089
34,AUS,CZE,2019,0.19000000,32.56314881,7.21023000,16.95998032,0.00000000,3.22239626,0.00000000
35,AUS,DEU,2019,0.29937781,720.35128869,"1,596.44298900",-0.00000000,876.09170031,-0.00000000,125.73768663
36,AUS,DNK,2019,0.22000000,26.76858325,1.00866800,17.23224292,0.00000000,3.79109344,0.00000000
37,AUS,ECU,2019,0.25000000,3.63277369,-6.84994700,7.01247608,0.00000000,1.75311902,0.00000000
38,AUS,EGY,2019,0.22500000,2.61419522,-0.37047600,1.99661292,0.00000000,0.44923791,0.00000000
39,AUS,ESP,2019,0.25000000,71.07833429,91.85767400,-0.00000000,20.77933971,-0.00000000,2.42146934
40,AUS,FIN,2019,0.20000000,5.55637838,3.30176400,1.50823721,0.00000000,0.30164744,0.00000000
41,AUS,FJI,2019,0.20000000,66.60612619,88.77965400,-0.00000000,0.00000000,-0.00000000,0.00000000
42,AUS,FRA,2019,0.34433333,"1,430.31793612",102.66098300,888.14372693,0.00000000,305.81748701,0.00000000
43,AUS,GBR,2019,0.19000000,"1,834.37079767","3,530.27091200",-0.00000000,"1,695.90011433",-0.00000000,162.67584008
44,AUS,GGY,2019,0.00000000,0.00000000,-91.65649500,61.31413757,0.00000000,0.00000000,0.00000000
45,AUS,GHA,2019,0.25000000,4.71664192,2.53744300,1.45778761,0.00000000,0.36444690,0.00000000
46,AUS,GRC,2019,0.24000000,2.23687362,8.76738900,-0.00000000,0.00000000,-0.00000000,0.00000000
47,AUS,HKG,2019,0.16500000,160.47839650,840.64890000,-0.00000000,680.17050350,-0.00000000,47.51505880
48,AUS,HUN,2019,0.09000000,4.19004250,7.05933100,-0.00000000,2.86928850,-0.00000000,0.35152768
49,AUS,IDN,2019,0.25000000,424.93265768,170.45981400,170.23106704,0.00000000,42.55776676,-0.00000000
50,AUS,IND,2019,0.40550000,519.56668981,129.12941800,261.18525038,0.00000000,105.91061903,0.00000000
51,AUS,IRL,2019,0.12500000,144.73683634,7.68658600,91.68055033,0.00000000,11.46006879,0.00000000
52,AUS,ITA,2019,0.27806400,35.29871889,89.79364800,-0.00000000,0.00000000,-0.00000000,0.00000000
53,AUS,JEY,2019,0.00000000,3.36344827,-44.72492300,32.16899153,0.00000000,0.00000000,0.00000000
54,AUS,JPN,2019,0.29740000,479.64480884,140.71635700,226.72813009,0.00000000,67.42894589,0.00000000
55,AUS,KOR,2019,0.27500000,41.81723928,93.70341800,-0.00000000,0.00000000,-0.00000000,0.00000000
56,AUS,LUX,2019,0.24940000,3.69473946,160.83499700,-0.00000000,157.14025754,-0.00000000,5.01321194
57,AUS,MAC,2019,0.12000000,3.37977403,9.42308200,-0.00000000,0.00000000,-0.00000000,0.00000000
58,AUS,MAR,2019,0.31000000,5.54709144,-3.22818800,5.87027347,0.00000000,1.81978478,0.00000000
59,AUS,MEX,2019,0.30000000,103.48757138,-82.23639500,124.24111160,0.00000000,37.27233348,0.00000000
60,AUS,MLT,2019,0.05000000,0.34785471,7.57713600,-0.00000000,7.22928129,-0.00000000,0.56362658
61,AUS,MMR,2019,0.25000000,7.19736655,-13.87896200,14.09913076,0.00000000,3.52478269,0.00000000
62,AUS,MNG,2019,0.25000000,20.71874315,5.95194200,9.87833625,0.00000000,2.46958406,0.00000000
63,AUS,MOZ,2019,0.32000000,30.29104270,-29.21805300,39.80895059,0.00000000,12.73886419,0.00000000
64,AUS,MUS,2019,0.15000000,0.33305848,0.03614900,0.19861930,0.00000000,0.02979289,0.00000000
65,AUS,MYS,2019,0.24000000,334.43917468,74.98255700,173.56499122,0.00000000,41.65559789,0.00000000
66,AUS,NAM,2019,0.32000000,3.95701496,0.89102700,2.05101022,0.00000000,0.65632327,0.00000000
67,AUS,NCL,2019,0.00000000,3.95294705,10.45209600,-0.00000000,0.00000000,-0.00000000,0.00000000
68,AUS,NLD,2019,0.25000000,135.15748820,138.96255600,-0.00000000,3.80506780,-0.00000000,0.31833671
69,AUS,NOR,2019,0.22000000,191.33280637,33.27926700,105.73082089,0.00000000,23.26078060,0.00000000
70,AUS,NZL,2019,0.28000000,"4,379.82427688","6,271.23989400",-0.00000000,0.00000000,-0.00000000,0.00000000
71,AUS,PAN,2019,0.25000000,3.84984303,10.16318700,-0.00000000,6.31334397,-0.00000000,0.45772601
72,AUS,PER,2019,0.29500000,28.52724354,-19.35956300,32.03415365,0.00000000,9.45007533,0.00000000
73,AUS,PHL,2019,0.30000000,386.90358732,75.57443300,208.26542185,0.00000000,62.47962656,0.00000000
74,AUS,PNG,2019,0.30000000,248.29483536,692.10703700,-0.00000000,443.81220164,-0.00000000,48.58851189
75,AUS,POL,2019,0.19000000,24.15297885,25.02088600,-0.00000000,0.00000000,-0.00000000,0.00000000
76,AUS,PRT,2019,0.31500000,20.65146063,28.42640500,-0.00000000,7.77494437,-0.00000000,0.97972019
77,AUS,ROU,2019,0.16000000,4.21443657,6.89664900,-0.00000000,2.68221243,-0.00000000,0.36452348
78,AUS,RUS,2019,0.20000000,45.75208693,6.49109000,26.26386888,0.00000000,5.25277378,0.00000000
79,AUS,SGP,2019,0.17000000,504.77574567,"1,410.39097800",-0.00000000,905.61523233,-0.00000000,59.40152054
80,AUS,SLB,2019,0.30000000,7.30758147,8.05173000,-0.00000000,0.74414853,-0.00000000,0.09937823
81,AUS,SVK,2019,0.21000000,1.57208831,-0.63040000,1.47336717,0.00000000,0.30940711,0.00000000
82,AUS,SWE,2019,0.21400000,438.81247822,28.46782200,274.50240926,0.00000000,58.74351558,0.00000000
83,AUS,THA,2019,0.20000000,158.89847246,-36.83155300,130.93472216,0.00000000,26.18694443,0.00000000
84,AUS,TLS,2019,0.10000000,7.24023143,45.96278000,-0.00000000,38.72254857,-0.00000000,4.56917155
85,AUS,TTO,2019,0.30000000,19.81059932,48.79752500,-0.00000000,0.00000000,-0.00000000,0.00000000
86,AUS,TUR,2019,0.22000000,33.68349357,17.24168000,10.99884540,0.00000000,2.41974599,0.00000000
87,AUS,TWN,2019,0.20000000,11.62248562,44.53172500,-0.00000000,32.90923938,-0.00000000,4.89291651
88,AUS,TZA,2019,0.30000000,3.00506087,-3.06191600,4.05853894,0.00000000,1.21756168,0.00000000
89,AUS,UKR,2019,0.18000000,22.45882720,8.33044800,9.45126023,0.00000000,1.70122684,0.00000000
90,AUS,USA,2019,0.27000000,"5,229.93683711","3,446.31883500","1,193.16148353",0.00000000,322.15360055,0.00000000
91,AUS,VGB,2019,0.00000000,759.32702435,33.73996000,485.38562468,0.00000000,0.00000000,0.00000000
92,AUS,VNM,2019,0.20000000,114.47345116,37.45277400,51.52342336,0.00000000,10.30468467,0.00000000
93,AUS,VUT,2019,0.00000000,5.08695284,-4.38103500,6.33366472,0.00000000,0.00000000,0.00000000
94,AUS,ZAF,2019,0.28000000,378.17202108,-520.27500200,601.02128464,0.00000000,168.28595970,0.00000000
95,AUS,ZMB,2019,0.35000000,3.26180400,0.47676700,1.86306646,0.00000000,0.65207326,0.00000000
96,AUS,ZWE,2019,0.25750000,759.32702435,0.02039800,507.94251891,0.00000000,130.79519862,0.00000000

In [8]:
# Count how many values in misalignment_final_estimates_australia_2019['iso_parent'] == 'AUS'
misalignment_australia_2019 = misalignment_final_estimates_australia_2019[misalignment_final_estimates_australia_2019['iso_parent'] == 'AUS']

# Count total values in misalignment_australia
misalignment_australia_2019['iso_partner'].count()

# Keep if positive_misalignment > 0
misalignment_australia_2019 = misalignment_australia_2019[misalignment_australia_2019['positive_misalignment'] > 0]
misalignment_australia_2019

# Export the results to excel
misalignment_australia_2019.to_csv(f'{output_tables}/Australia/australia_request_2019.csv', index=False)

## Australia in 2020

In [5]:
# Load the data
final_misalignment_2020 = pd.read_csv(f'{output_tables}/Datasets_to_Perform_Analysis/misalignment_dataset_2020.csv') 

# Start the estimates
misalignment_final_estimates_australia_2020 = final_misalignment_2020[final_misalignment_2020['year'] == 2020].copy()
misalignment_final_estimates_australia_2020 = calculate_misalignment(misalignment_final_estimates_australia_2020, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Generate a new column called negative_misalignment equal to misaligned_profit if misaligned_profit < 0 and a new column called positive_misalignment equal to misaligned_profit if misaligned_profit > 0
misalignment_final_estimates_australia_2020['negative_misalignment'] = misalignment_final_estimates_australia_2020['misaligned_profit'].apply(lambda x: x if x < 0 else 0)
misalignment_final_estimates_australia_2020['positive_misalignment'] = misalignment_final_estimates_australia_2020['misaligned_profit'].apply(lambda x: x if x > 0 else 0)

# Rename profit_loss_before_income_tax_corrected to reported_profit
misalignment_final_estimates_australia_2020 = misalignment_final_estimates_australia_2020.rename(columns={'profit_loss_before_income_tax_corrected': 'reported_profit'})

# Convert results to millions
misalignment_final_estimates_australia_2020['negative_misalignment'] = -misalignment_final_estimates_australia_2020['negative_misalignment'] / 1e6
misalignment_final_estimates_australia_2020['positive_misalignment'] = misalignment_final_estimates_australia_2020['positive_misalignment'] / 1e6
misalignment_final_estimates_australia_2020['theoretical_profit'] = misalignment_final_estimates_australia_2020['theoretical_profit'] / 1e6
misalignment_final_estimates_australia_2020['reported_profit'] = misalignment_final_estimates_australia_2020['reported_profit'] / 1e6

# Calculate other relevant variables
misalignment_final_estimates_australia_2020['tax_revenue_loss'] = misalignment_final_estimates_australia_2020['negative_misalignment'] * misalignment_final_estimates_australia_2020['cit']
misalignment_final_estimates_australia_2020['tax_revenue_gain'] = misalignment_final_estimates_australia_2020['positive_misalignment'] * misalignment_final_estimates_australia_2020['etr_average_corrected']

# Keep iso_partner, iso_parent, year, negative_misalignment, positive_misalignment, tax_revenue_loss, tax_revenue gain
misalignment_final_estimates_australia_2020 = misalignment_final_estimates_australia_2020[['iso_parent', 'iso_partner', 'year', 'cit', 'theoretical_profit', 'reported_profit', 'negative_misalignment', 'positive_misalignment', 'tax_revenue_loss', 'tax_revenue_gain']]

# Sort by iso_partner and then iso_parent
misalignment_final_estimates_australia_2020 = misalignment_final_estimates_australia_2020.sort_values(by=['iso_parent', 'iso_partner'])   

# Display 8 decimals
pd.options.display.float_format = '{:,.8f}'.format
pd.set_option('display.max_rows', None)
misalignment_final_estimates_australia_2020[(misalignment_final_estimates_australia_2020['iso_parent'] == 'AUS')] #| (misalignment_final_estimates_australia_2020['iso_partner'] == 'AUS')]

/var/folders/kj/y_rfkb696353czt_6gnx_jkc0000gn/T/ipykernel_7742/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,cit,theoretical_profit,reported_profit,negative_misalignment,positive_misalignment,tax_revenue_loss,tax_revenue_gain
17,AUS,ARE,2020,0.00000000,48.83834046,4.45462587,18.80006457,0.00000000,0.00000000,0.00000000
18,AUS,ARG,2020,0.30000000,38.15287173,52.32911780,-0.00000000,0.00000000,-0.00000000,0.00000000
19,AUS,AUS,2020,0.30000000,"67,318.17155651","73,328.77534400",-0.00000000,0.00000000,-0.00000000,0.00000000
20,AUS,AUT,2020,0.25000000,29.18371749,-26.38515424,23.53787614,0.00000000,5.88446904,0.00000000
21,AUS,BEL,2020,0.25000000,110.81808247,96.81298491,5.93228262,0.00000000,1.48307065,0.00000000
22,AUS,BGR,2020,0.10000000,7.07102467,28.09674011,-0.00000000,21.02571544,-0.00000000,1.64705981
23,AUS,BMU,2020,0.00000000,1.90300661,183.79405590,-0.00000000,181.89104929,-0.00000000,2.31614696
24,AUS,BRA,2020,0.34000000,128.42084651,-149.57894820,117.75522034,0.00000000,40.03677491,0.00000000
25,AUS,BWA,2020,0.22000000,5.93600835,0.31734573,2.37995447,0.00000000,0.52358998,0.00000000
26,AUS,CAN,2020,0.26250000,852.60595861,-787.87156200,694.87386528,0.00000000,182.40438964,0.00000000
27,AUS,CHE,2020,0.21148581,262.99456111,"1,413.84174400",-0.00000000,"1,150.84718289",-0.00000000,87.00927608
28,AUS,CHL,2020,0.27000000,"1,099.28643266","1,436.35934500",-0.00000000,0.00000000,-0.00000000,0.00000000
29,AUS,CHN,2020,0.25000000,439.19762381,193.18004100,104.20818728,0.00000000,26.05204682,0.00000000
30,AUS,CIV,2020,0.25000000,1.96990047,0.47497467,0.63322103,0.00000000,0.15830526,0.00000000
31,AUS,COL,2020,0.32000000,50.96455719,94.33097494,-0.00000000,0.00000000,-0.00000000,0.00000000
32,AUS,CRI,2020,0.30000000,0.44075153,0.36569785,0.03179125,0.00000000,0.00953738,0.00000000
33,AUS,CYM,2020,0.00000000,0.22429445,171.81692750,-0.00000000,171.59263305,-0.00000000,1.00180789
34,AUS,CYP,2020,0.12500000,0.00000000,-0.69086662,0.29263745,0.00000000,0.03657968,0.00000000
35,AUS,CZE,2020,0.19000000,34.33122049,7.04216211,11.55910595,0.00000000,2.19623013,0.00000000
36,AUS,DEU,2020,0.29830331,944.64448928,611.69559370,141.03057378,0.00000000,42.06988697,0.00000000
37,AUS,DNK,2020,0.22000000,29.57225224,-0.59621998,12.77876877,0.00000000,2.81132913,0.00000000
38,AUS,ECU,2020,0.25000000,5.62530514,-10.78351680,6.95045277,0.00000000,1.73761319,0.00000000
39,AUS,EGY,2020,0.22500000,14.78088883,11.30436393,1.47258726,0.00000000,0.33133213,0.00000000
40,AUS,ESP,2020,0.25000000,82.76825772,39.86245781,18.17404911,0.00000000,4.54351228,0.00000000
41,AUS,FIN,2020,0.20000000,5.87750571,1.90279724,1.68360797,0.00000000,0.33672159,0.00000000
42,AUS,FJI,2020,0.20000000,65.27274125,27.31145903,16.07964911,0.00000000,3.21592982,0.00000000
43,AUS,FRA,2020,0.32023000,"1,227.02634813",74.31557575,488.26550800,0.00000000,156.35726363,0.00000000
44,AUS,GAB,2020,0.30000000,0.50766751,-1.06834398,0.66756733,0.00000000,0.20027020,0.00000000
45,AUS,GBR,2020,0.19000000,"1,783.99423603","4,969.76486500",-0.00000000,"3,185.77062897",-0.00000000,321.75209426
46,AUS,GGY,2020,0.00000000,891.45060200,186.22247780,298.72069956,0.00000000,0.00000000,0.00000000
47,AUS,GHA,2020,0.25000000,66.57416923,38.75458250,11.78382728,0.00000000,2.94595682,0.00000000
48,AUS,GIN,2020,0.35000000,0.98839757,1.59576205,-0.00000000,0.60736448,-0.00000000,0.02344450
49,AUS,GRC,2020,0.24000000,2.37222703,-5.07915050,3.15625629,0.00000000,0.75750151,0.00000000
50,AUS,HKG,2020,0.16500000,187.43317493,218.17393750,-0.00000000,30.74076257,-0.00000000,2.10836895
51,AUS,HUN,2020,0.09000000,9.67192311,3.39794540,2.65753299,0.00000000,0.23917797,0.00000000
52,AUS,IDN,2020,0.22000000,438.22000482,199.58226410,101.08223198,0.00000000,22.23809104,-0.00000000
53,AUS,IND,2020,0.25170000,578.31376377,179.68371900,168.85181086,0.00000000,42.50000079,0.00000000
54,AUS,IRL,2020,0.12500000,163.82227327,71.44928273,39.12737369,0.00000000,4.89092171,0.00000000
55,AUS,ITA,2020,0.27810000,38.42888188,92.56010020,-0.00000000,0.00000000,-0.00000000,0.00000000
56,AUS,JEY,2020,0.00000000,3.09462090,36.41213830,-0.00000000,33.31751740,-0.00000000,0.05019531
57,AUS,JPN,2020,0.29740000,89.50622975,203.78343670,-0.00000000,0.00000000,-0.00000000,0.00000000
58,AUS,KAZ,2020,0.20000000,37.64126097,30.85784084,2.87332274,0.00000000,0.57466455,0.00000000
59,AUS,KHM,2020,0.20000000,2.63557693,9.17411503,-0.00000000,0.00000000,-0.00000000,0.00000000
60,AUS,KOR,2020,0.27500000,21.78757367,40.63288591,-0.00000000,0.00000000,-0.00000000,0.00000000
61,AUS,LAO,2020,0.24000000,14.93118553,10.40479907,1.91728787,0.00000000,0.46014909,0.00000000
62,AUS,LBR,2020,0.25000000,0.51910246,-0.94114257,0.61853094,0.00000000,0.15463274,0.00000000
63,AUS,LUX,2020,0.24940000,4.25910462,203.91960060,-0.00000000,199.66049598,-0.00000000,7.06542420
64,AUS,MAC,2020,0.12000000,2.86617708,5.57397644,-0.00000000,0.00000000,-0.00000000,0.00000000
65,AUS,MAR,2020,0.31000000,9.63114903,5.01455747,1.95549697,0.00000000,0.60620406,0.00000000
66,AUS,MEX,2020,0.30000000,101.38071502,-133.93277940,99.67414693,0.00000000,29.90224408,0.00000000
67,AUS,MLI,2020,0.30000000,39.06580079,10.81804648,11.96519061,0.00000000,3.58955718,0.00000000
68,AUS,MLT,2020,0.05000000,0.32689035,5.61142351,-0.00000000,5.28453317,-0.00000000,0.35662732
69,AUS,MMR,2020,0.25000000,5.09433959,-35.54598297,17.21443767,0.00000000,4.30360942,0.00000000
70,AUS,MNG,2020,0.25000000,19.43655757,16.20333916,1.36952744,0.00000000,0.34238186,0.00000000
71,AUS,MOZ,2020,0.32000000,29.75376705,-27.52074348,24.26035103,0.00000000,7.76331233,0.00000000
72,AUS,MUS,2020,0.15000000,0.12318751,-1.91324098,0.86259087,0.00000000,0.12938863,0.00000000
73,AUS,MYS,2020,0.24000000,215.12651155,61.69424992,64.99087452,0.00000000,15.59780989,0.00000000
74,AUS,NAM,2020,0.32000000,1.88185668,0.10065073,0.75448365,0.00000000,0.24143477,0.00000000
75,AUS,NCL,2020,0.00000000,3.86462498,8.80867659,-0.00000000,0.00000000,-0.00000000,0.00000000
76,AUS,NLD,2020,0.25000000,134.21397763,-135.86859270,114.40164052,0.00000000,28.60041013,0.00000000
77,AUS,NOR,2020,0.22000000,200.29681626,38.88448945,68.37107246,0.00000000,15.04163594,0.00000000
78,AUS,NZL,2020,0.28000000,"4,286.13384486","5,080.46798100",-0.00000000,0.00000000,-0.00000000,0.00000000
79,AUS,PAN,2020,0.25000000,4.83404270,-0.73867054,2.36049122,0.00000000,0.59012281,0.00000000
80,AUS,PER,2020,0.29500000,72.67887817,-17.41409205,38.16160213,0.00000000,11.25767263,0.00000000
81,AUS,PHL,2020,0.30000000,485.47314546,62.28353352,179.25475827,0.00000000,53.77642748,0.00000000
82,AUS,PNG,2020,0.30000000,245.63803411,397.73250760,-0.00000000,152.09447349,-0.00000000,17.25294386
83,AUS,POL,2020,0.19000000,31.58761779,20.42980763,4.72622793,0.00000000,0.89798331,0.00000000
84,AUS,PRT,2020,0.31500000,10.95293792,3.06943279,3.33929701,0.00000000,1.05187856,0.00000000
85,AUS,ROU,2020,0.16000000,5.20166719,-4.14479599,3.95897714,0.00000000,0.63343634,0.00000000
86,AUS,RUS,2020,0.20000000,56.20927706,18.62105491,15.92162824,0.00000000,3.18432565,0.00000000
87,AUS,SAU,2020,0.20000000,86.21919687,7.99385223,33.13471042,0.00000000,6.62694208,0.00000000
88,AUS,SEN,2020,0.30000000,17.32703170,-2.23040610,8.28414424,0.00000000,2.48524327,0.00000000
89,AUS,SGP,2020,0.17000000,488.16077304,756.75290730,-0.00000000,268.59213426,-0.00000000,20.25233998
90,AUS,SLB,2020,0.30000000,7.03261269,1.04249258,2.53729652,0.00000000,0.76118896,0.00000000
91,AUS,SRB,2020,0.15000000,2.08436846,-2.74556251,2.04586333,0.00000000,0.30687950,0.00000000
92,AUS,SVK,2020,0.21000000,1.62928436,2.51075080,-0.00000000,0.88146644,-0.00000000,0.07807996
93,AUS,SWE,2020,0.21400000,462.76408117,14.33805053,189.94440660,0.00000000,40.64810301,0.00000000
94,AUS,THA,2020,0.20000000,68.14133830,40.20222791,11.83445514,0.00000000,2.36689103,0.00000000
95,AUS,TLS,2020,0.10000000,3.56719318,-130.40423980,56.74765201,0.00000000,5.67476520,0.00000000
96,AUS,TTO,2020,0.30000000,13.39589136,-37.06044423,21.37230684,0.00000000,6.41169205,0.00000000
97,AUS,TUR,2020,0.22000000,26.44516803,9.23624339,7.28936046,0.00000000,1.60365930,0.00000000
98,AUS,TWN,2020,0.20000000,12.04245725,75.33838408,-0.00000000,63.29592683,-0.00000000,9.47176593
99,AUS,TZA,2020,0.30000000,12.02854374,19.36701041,-0.00000000,0.00000000,-0.00000000,0.00000000
100,AUS,UKR,2020,0.18000000,25.49661601,-9.41435627,14.78759809,0.00000000,2.66176766,0.00000000
101,AUS,URY,2020,0.25000000,0.00000000,-1.57392156,0.66668208,0.00000000,0.16667052,0.00000000
102,AUS,USA,2020,0.27000000,"5,121.52242667","1,389.88821100","1,580.64652437",0.00000000,426.77456158,0.00000000
103,AUS,VEN,2020,0.34000000,0.62013092,30.02688380,-0.00000000,0.00000000,-0.00000000,0.00000000
104,AUS,VGB,2020,0.00000000,891.45060200,17.77251137,370.07277712,0.00000000,0.00000000,0.00000000
105,AUS,VNM,2020,0.20000000,94.98705493,53.62863175,17.51861090,0.00000000,3.50372218,0.00000000
106,AUS,VUT,2020,0.00000000,5.25791433,2.12739584,1.32602578,0.00000000,0.00000000,0.00000000
107,AUS,ZAF,2020,0.28000000,480.54398974,27.75050637,191.79437329,0.00000000,53.70242452,0.00000000
108,AUS,ZMB,2020,0.35000000,3.24239359,-6.39484876,4.08214545,0.00000000,1.42875091,0.00000000
109,AUS,ZWE,2020,0.24720000,0.00000000,-0.18488180,0.07831228,0.00000000,0.01935880,0.00000000

In [6]:
# Count how many values in misalignment_final_estimates_australia_2020['iso_parent'] == 'AUS'
misalignment_australia_2020 = misalignment_final_estimates_australia_2020[misalignment_final_estimates_australia_2020['iso_parent'] == 'AUS']

# Count total values in misalignment_australia
misalignment_australia_2020['iso_partner'].count()

# Keep if positive_misalignment > 0
misalignment_australia_2020 = misalignment_australia_2020[misalignment_australia_2020['positive_misalignment'] > 0]
misalignment_australia_2020

# Export the results to excel
misalignment_australia_2020.to_csv(f'{output_tables}/Australia/australia_request_2020.csv', index=False)

## Australia in 2021

In [3]:
# Load the data
final_misalignment_2021 = pd.read_csv(f'{output_tables}/Datasets_to_Perform_Analysis/misalignment_dataset_2021.csv') 

# Start the estimates
misalignment_final_estimates_australia_2021 = final_misalignment_2021[final_misalignment_2021['year'] == 2021].copy()
misalignment_final_estimates_australia_2021 = calculate_misalignment(misalignment_final_estimates_australia_2021, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Generate a new column called negative_misalignment equal to misaligned_profit if misaligned_profit < 0 and a new column called positive_misalignment equal to misaligned_profit if misaligned_profit > 0
misalignment_final_estimates_australia_2021['negative_misalignment'] = misalignment_final_estimates_australia_2021['misaligned_profit'].apply(lambda x: x if x < 0 else 0)
misalignment_final_estimates_australia_2021['positive_misalignment'] = misalignment_final_estimates_australia_2021['misaligned_profit'].apply(lambda x: x if x > 0 else 0)

# Rename profit_loss_before_income_tax_corrected to reported_profit
misalignment_final_estimates_australia_2021 = misalignment_final_estimates_australia_2021.rename(columns={'profit_loss_before_income_tax_corrected': 'reported_profit'})

# Convert results to millions
misalignment_final_estimates_australia_2021['negative_misalignment'] = -misalignment_final_estimates_australia_2021['negative_misalignment'] / 1e6
misalignment_final_estimates_australia_2021['positive_misalignment'] = misalignment_final_estimates_australia_2021['positive_misalignment'] / 1e6
misalignment_final_estimates_australia_2021['theoretical_profit'] = misalignment_final_estimates_australia_2021['theoretical_profit'] / 1e6
misalignment_final_estimates_australia_2021['reported_profit'] = misalignment_final_estimates_australia_2021['reported_profit'] / 1e6

# Calculate other relevant variables
misalignment_final_estimates_australia_2021['tax_revenue_loss'] = misalignment_final_estimates_australia_2021['negative_misalignment'] * misalignment_final_estimates_australia_2021['cit']
misalignment_final_estimates_australia_2021['tax_revenue_gain'] = misalignment_final_estimates_australia_2021['positive_misalignment'] * misalignment_final_estimates_australia_2021['etr_average_corrected']

# Keep iso_partner, iso_parent, year, negative_misalignment, positive_misalignment, tax_revenue_loss, tax_revenue gain
misalignment_final_estimates_australia_2021 = misalignment_final_estimates_australia_2021[['iso_parent', 'iso_partner', 'year', 'cit', 'theoretical_profit', 'reported_profit', 'negative_misalignment', 'positive_misalignment', 'tax_revenue_loss', 'tax_revenue_gain']]

# Sort by iso_partner and then iso_parent
misalignment_final_estimates_australia_2021 = misalignment_final_estimates_australia_2021.sort_values(by=['iso_parent', 'iso_partner'])   

# Display 8 decimals
pd.options.display.float_format = '{:,.8f}'.format
pd.set_option('display.max_rows', None)
misalignment_final_estimates_australia_2021[(misalignment_final_estimates_australia_2021['iso_parent'] == 'AUS')] #| (misalignment_final_estimates_australia_2021['iso_partner'] == 'AUS')]

/var/folders/kj/y_rfkb696353czt_6gnx_jkc0000gn/T/ipykernel_7742/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,cit,theoretical_profit,reported_profit,negative_misalignment,positive_misalignment,tax_revenue_loss,tax_revenue_gain
168,AUS,ARE,2021,0.00000000,68.74847172,17.53242900,15.70545568,0.00000000,0.00000000,0.00000000
169,AUS,ARG,2021,0.30000000,45.09391400,17.31457100,8.51856600,0.00000000,2.55556980,0.00000000
170,AUS,AUS,2021,0.30000000,"89,671.85985969","95,005.12027700",-0.00000000,0.00000000,-0.00000000,0.00000000
171,AUS,AUT,2021,0.25000000,21.71374916,18.83311000,0.88335116,0.00000000,0.22083779,0.00000000
172,AUS,BEL,2021,0.25000000,157.71122982,207.31682900,-0.00000000,49.60559918,-0.00000000,6.86889198
173,AUS,BGR,2021,0.10000000,10.08242509,18.14296600,-0.00000000,8.06054091,-0.00000000,0.68007429
174,AUS,BMU,2021,0.00000000,2.05013955,441.42198600,-0.00000000,439.37184645,-0.00000000,6.22651597
175,AUS,BRA,2021,0.34000000,163.26747484,19.71960200,44.01911265,0.00000000,14.96649830,0.00000000
176,AUS,BWA,2021,0.22000000,13.90458954,23.98282900,-0.00000000,0.00000000,-0.00000000,0.00000000
177,AUS,CAN,2021,0.26170000,"1,309.28379413",-613.27364200,589.55434648,0.00000000,154.28637247,0.00000000
178,AUS,CHE,2021,0.19698516,332.15123444,898.43048500,-0.00000000,566.27925056,-0.00000000,39.11184859
179,AUS,CHL,2021,0.27000000,"1,237.76013978","4,195.51137100",-0.00000000,0.00000000,-0.00000000,0.00000000
180,AUS,CHN,2021,0.25000000,479.42045179,-161.38779700,196.50455234,0.00000000,49.12613809,0.00000000
181,AUS,CIV,2021,0.25000000,1.69589253,-0.18217100,0.57591024,0.00000000,0.14397756,0.00000000
182,AUS,COL,2021,0.31000000,57.95497441,107.64292300,-0.00000000,0.00000000,-0.00000000,0.00000000
183,AUS,CRI,2021,0.30000000,0.89489707,-1.06820300,0.60198679,0.00000000,0.18059604,0.00000000
184,AUS,CYM,2021,0.00000000,"1,206.49806524","2,052.28077100",-0.00000000,845.78270576,-0.00000000,5.20780283
185,AUS,CZE,2021,0.19000000,50.95228697,17.33920000,10.30748999,0.00000000,1.95842310,0.00000000
186,AUS,DEU,2021,0.29941208,"1,299.50385344","1,153.05565300",44.90850129,0.00000000,13.44614778,0.00000000
187,AUS,DNK,2021,0.22000000,43.09250148,13.41569500,9.10042526,0.00000000,2.00209356,0.00000000
188,AUS,ECU,2021,0.25000000,14.53500331,-10.32744600,7.62409735,0.00000000,1.90602434,0.00000000
189,AUS,EGY,2021,0.22500000,13.72864286,12.85279800,0.26857879,0.00000000,0.06043023,0.00000000
190,AUS,ESP,2021,0.25000000,122.91634007,52.68373000,21.53690691,0.00000000,5.38422673,0.00000000
191,AUS,FIN,2021,0.20000000,11.96857151,0.48495900,3.52146237,0.00000000,0.70429247,0.00000000
192,AUS,FJI,2021,0.20000000,64.38985308,36.43750300,8.57161881,0.00000000,1.71432376,0.00000000
193,AUS,FRA,2021,0.28407500,"2,188.57062635",170.30737600,618.90263938,0.00000000,175.81476728,0.00000000
194,AUS,GBR,2021,0.19000000,"2,576.99008510","2,108.84985900",143.55571380,0.00000000,27.27558562,0.00000000
195,AUS,GGY,2021,0.00000000,"1,206.49806524",127.34205800,330.92437325,0.00000000,0.00000000,0.00000000
196,AUS,GHA,2021,0.25000000,72.24404981,0.38420000,22.03590176,0.00000000,5.50897544,0.00000000
197,AUS,GRC,2021,0.22000000,2.47327836,5.59084500,-0.00000000,0.00000000,-0.00000000,0.00000000
198,AUS,HKG,2021,0.16500000,199.99689092,708.25425300,-0.00000000,508.25736208,-0.00000000,33.41245119
199,AUS,HUN,2021,0.09000000,6.58055825,10.37484900,-0.00000000,3.79429075,-0.00000000,0.48056943
200,AUS,IDN,2021,0.22000000,660.50693014,288.50050700,114.07617768,0.00000000,25.09675909,0.00000000
201,AUS,IND,2021,0.25170000,946.09411846,159.01576300,241.35844098,0.00000000,60.74991959,0.00000000
202,AUS,IRL,2021,0.12500000,241.80309776,-57.44111300,91.76356544,0.00000000,11.47044568,0.00000000
203,AUS,ISR,2021,0.23000000,18.25525331,89.36869500,-0.00000000,0.00000000,-0.00000000,0.00000000
204,AUS,ITA,2021,0.27810000,61.89608812,127.57138500,-0.00000000,0.00000000,-0.00000000,0.00000000
205,AUS,JEY,2021,0.00000000,4.00890986,55.58060900,-0.00000000,51.57169914,-0.00000000,0.06558102
206,AUS,JPN,2021,0.29740000,118.22423443,231.71843900,-0.00000000,0.00000000,-0.00000000,0.00000000
207,AUS,KAZ,2021,0.20000000,49.76332532,25.83589400,7.33737306,0.00000000,1.46747461,0.00000000
208,AUS,KOR,2021,0.27500000,26.30801096,7.16958800,5.86881839,0.00000000,1.61392506,0.00000000
209,AUS,LUX,2021,0.24940000,8.10719316,8.42968900,-0.00000000,0.32249584,-0.00000000,0.01200674
210,AUS,MAC,2021,0.12000000,4.20081622,-4.59667300,2.69775972,0.00000000,0.32373117,0.00000000
211,AUS,MAR,2021,0.31000000,140.37734078,22.38360900,36.18290727,0.00000000,11.21670125,0.00000000
212,AUS,MEX,2021,0.30000000,181.87526476,-203.19654600,118.08269312,0.00000000,35.42480794,0.00000000
213,AUS,MLT,2021,0.05000000,0.83287713,401.21100300,-0.00000000,400.37812587,-0.00000000,26.48271297
214,AUS,MMR,2021,0.25000000,3.60684116,-250.59993600,77.95278703,0.00000000,19.48819676,0.00000000
215,AUS,MNG,2021,0.25000000,34.34837736,61.91789000,-0.00000000,27.56951264,-0.00000000,2.79278095
216,AUS,MOZ,2021,0.32000000,39.04092054,53.72025100,-0.00000000,0.00000000,-0.00000000,0.00000000
217,AUS,MUS,2021,0.15000000,"1,206.49806524",82.13606300,344.78684120,0.00000000,51.71802618,0.00000000
218,AUS,MYS,2021,0.24000000,453.65322097,168.34606400,87.48975261,0.00000000,20.99754063,0.00000000
219,AUS,NAM,2021,0.32000000,3.97094783,2.40150600,0.48127106,0.00000000,0.15400674,0.00000000
220,AUS,NCL,2021,0.00000000,5.01444547,5.61102500,-0.00000000,0.00000000,-0.00000000,0.00000000
221,AUS,NLD,2021,0.25000000,188.05317267,131.42427900,17.36531236,0.00000000,4.34132809,0.00000000
222,AUS,NOR,2021,0.22000000,356.36205672,34.51112200,98.69594214,0.00000000,21.71310727,0.00000000
223,AUS,NZL,2021,0.28000000,"6,214.09604596","7,300.95830000",-0.00000000,0.00000000,-0.00000000,0.00000000
224,AUS,PAN,2021,0.25000000,3.04802165,-2.34838000,1.65481248,0.00000000,0.41370312,0.00000000
225,AUS,PER,2021,0.29500000,87.96354912,5.03070400,25.43144792,0.00000000,7.50227714,0.00000000
226,AUS,PHL,2021,0.30000000,546.40959182,34.93149500,156.84531939,0.00000000,47.05359582,0.00000000
227,AUS,PNG,2021,0.30000000,382.80581589,-819.17871700,368.58987536,0.00000000,110.57696261,0.00000000
228,AUS,POL,2021,0.19000000,41.86417426,52.96968600,-0.00000000,0.00000000,-0.00000000,0.00000000
229,AUS,PRT,2021,0.31500000,24.45499147,22.31698000,0.65562356,0.00000000,0.20652142,0.00000000
230,AUS,ROU,2021,0.16000000,8.93706954,9.91156400,-0.00000000,0.97449446,-0.00000000,0.12806259
231,AUS,RUS,2021,0.20000000,88.57260913,20.98181800,20.72679024,0.00000000,4.14535805,0.00000000
232,AUS,SAU,2021,0.20000000,104.03722573,12.18675400,28.16604790,0.00000000,5.63320958,0.00000000
233,AUS,SEN,2021,0.30000000,21.69715954,-10.68723700,9.93071072,0.00000000,2.97921322,0.00000000
234,AUS,SGP,2021,0.17000000,659.04255813,"1,829.04561300",-0.00000000,"1,170.00305487",-0.00000000,79.34111191
235,AUS,SLB,2021,0.30000000,10.68102448,2.38273800,2.54467865,0.00000000,0.76340360,0.00000000
236,AUS,SRB,2021,0.15000000,3.15768630,-0.25372500,1.04611302,0.00000000,0.15691695,0.00000000
237,AUS,SVK,2021,0.21000000,2.66397422,2.89966700,-0.00000000,0.23569278,-0.00000000,0.01773448
238,AUS,SWE,2021,0.20600000,630.45800743,58.19637400,175.48465756,0.00000000,36.14983946,0.00000000
239,AUS,THA,2021,0.20000000,201.36152887,73.01271000,39.35830608,0.00000000,7.87166122,0.00000000
240,AUS,TLS,2021,0.10000000,5.50524371,627.89537400,-0.00000000,622.39013029,-0.00000000,67.04926271
241,AUS,TUR,2021,0.25000000,35.01925557,24.43065200,3.24700690,0.00000000,0.81175172,0.00000000
242,AUS,TWN,2021,0.20000000,14.74239124,4.41866300,3.16578259,0.00000000,0.63315652,0.00000000
243,AUS,TZA,2021,0.30000000,15.25651979,16.01018800,-0.00000000,0.00000000,-0.00000000,0.00000000
244,AUS,URY,2021,0.25000000,"1,206.49806524",0.16474300,369.92343639,0.00000000,92.48085910,0.00000000
245,AUS,USA,2021,0.27000000,"7,200.42273180","8,095.39649900",-0.00000000,0.00000000,-0.00000000,0.00000000
246,AUS,VGB,2021,0.00000000,0.00000000,-151.95434100,46.59696533,0.00000000,0.00000000,0.00000000
247,AUS,VNM,2021,0.20000000,157.33588052,80.33542300,23.61227475,0.00000000,4.72245495,0.00000000
248,AUS,VUT,2021,0.00000000,5.66948241,6.20128200,-0.00000000,0.53179959,-0.00000000,0.00000000
249,AUS,ZAF,2021,0.28000000,388.30743975,88.16859200,92.03790686,0.00000000,25.77061392,0.00000000
250,AUS,ZMB,2021,0.35000000,6.19793982,-7.98825800,4.35021312,0.00000000,1.52257459,0.00000000
251,AUS,ZWE,2021,0.24720000,2.25938367,4.96064300,-0.00000000,0.00000000,-0.00000000,0.00000000

In [4]:
# Count how many values in misalignment_final_estimates_spain_2021['iso_parent'] == 'AUS'
misalignment_australia_2021 = misalignment_final_estimates_australia_2021[misalignment_final_estimates_australia_2021['iso_parent'] == 'AUS']

# Count total values in misalignment_australia
misalignment_australia_2021['iso_partner'].count()

# Keep if positive_misalignment > 0
misalignment_australia_2021 = misalignment_australia_2021[misalignment_australia_2021['positive_misalignment'] > 0]
misalignment_australia_2021

# Export the results to excel
misalignment_australia_2021.to_csv(f'{output_tables}/Australia/australia_request_2021.csv', index=False)